# Generated by Django 3.0.5 on 2020-06-08 18:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 initial = True

 dependencies = [
  ('anon_app', '0001_initial'),
 ]

 operations = [
  migrations.CreateModel(
   name='LemmingsTask',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('action', models.CharField(choices=[('create_vk_bot', 'Создать бота в vk.com'), ('create_twitter_bot', 'Создать бота в twitter.com'), ('create_instagram_bot', 'Создать бота в instagram.com'), ('login_vk_bot', 'Авторизовать бота в vk.com'), ('login_twitter_bot', 'Авторизовать бота в twitter.com'), ('login_instagram_bot', 'Авторизовать бота в instagram.com')], max_length=79, verbose_name='Тип задачи')),
    ('kwargs', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Входные данные')),
    ('task_id', models.CharField(max_length=128, null=True, verbose_name='ID задачи celery')),
    ('chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='anon_app.Chain', verbose_name='Цепочка анонимизации')),
   ],
  ),
 ]