# Generated by Django 3.0.5 on 2020-07-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0002_chain_task_queue_name'),
  ('lemmings_app', '0001_initial'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='chain',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anon_app.Chain', verbose_name='Цепочка анонимизации'),
  ),
 ]