# Generated by Django 3.1 on 2020-08-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0002_auto_20200708_1507'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='kwargs',
   field=models.JSONField(null=True, verbose_name='Входные данные'),
  ),
 ]