# Generated by Django 3.1 on 2020-08-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0003_auto_20200810_1215'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='kwargs',
   field=models.JSONField(default=dict, verbose_name='Входные данные'),
  ),
 ]