# Generated by Django 3.1 on 2020-09-24 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0009_auto_20200819_1751'),
  ('lemmings_app', '0006_lemmingstask_result'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='chain',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmgs_tasks', to='anon_app.chain', verbose_name='Цепочка анонимизации'),
  ),
 ]