# Generated by Django 3.1.2 on 2020-10-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0007_auto_20200924_1217'),
 ]

 operations = [
  migrations.AlterModelOptions(
   name='lemmingstask',
   options={'ordering': ['-id']},
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(choices=[('create_vk_bot', 'Создать бота в vk.com'),
           ('create_twitter_bot', 'Создать бота в twitter.com'),
           ('create_instagram_bot', 'Создать бота в instagram.com'), (
           'create_instagram_bot_by_selenium',
           'Создать бота в instagram.com через браузер'),
           ('create_facebook_bot', 'Создать бота в facebook.com'),
           ('login_vk_bot', 'Авторизовать бота в vk.com'),
           ('login_twitter_bot', 'Авторизовать бота в twitter.com'),
           ('login_instagram_bot', 'Авторизовать бота в instagram.com'), (
           'login_instagram_bot_by_selenium',
           'Авторизовать бота в instagram.com через браузер'),
           ('login_facebook_bot', 'Авторизовать бота в facebook.com')], max_length=79,
          verbose_name='Тип задачи'),
  ),
 ]