# Generated by Django 3.1.2 on 2020-10-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0008_auto_20201028_0743'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='kwargs',
   field=models.JSONField(blank=True, default=dict, verbose_name='Входные данные'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='result',
   field=models.JSONField(blank=True, default=dict, verbose_name='Результат задачи'),
  ),
 ]