# Generated by Django 3.1.3 on 2020-11-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 replaces = [('lemmings_app', '0010_auto_20201103_0843'), ('lemmings_app', '0011_auto_20201103_1215')]

 dependencies = [
  ('lemmings_app', '0009_auto_20201029_0904'),
  ('anon_app', '0017_auto_20201103_1215'),
  ('anon_app', '0016_auto_20201028_1602'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(
    choices=[('create_vk_bot', 'Создать бота в vk.com'), ('login_vk_bot', 'Авторизовать бота в vk.com'),
       ('create_twitter_bot', 'Создать бота в twitter.com'),
       ('login_twitter_bot', 'Авторизовать бота в twitter.com'),
       ('create_instagram_bot', 'Создать бота в instagram.com'),
       ('login_instagram_bot', 'Авторизовать бота в instagram.com'),
       ('login_instagram_bot_by_selenium', 'Авторизовать бота в instagram.com через браузер'),
       ('create_instagram_bot_by_selenium', 'Создать бота в instagram.com через браузер'),
       ('create_facebook_bot', 'Создать бота в facebook.com'),
       ('login_facebook_bot', 'Авторизовать бота в facebook.com'),
       ('create_mail_ru_bot', 'Создать бота в "Мой мир"'),
       ('login_mail_ru_bot', 'Авторизовать бота в "Мой мир"')], max_length=79,
    verbose_name='Тип задачи'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='chain',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lmgs_tasks',
         to='anon_app.chain', verbose_name='Цепочка анонимизации'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='chain',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
         related_name='lmgs_tasks', to='anon_app.chain',
         verbose_name='Цепочка анонимизации'),
  ),
 ]