# Generated by Django 3.1.1 on 2020-11-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0008_auto_20201103_1547'),
  ('lemmings_app', '0010_auto_20201103_0843_squashed_0011_auto_20201103_1215'),
 ]

 operations = [
 ]