# Generated by Django 3.1.1 on 2020-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0011_merge_20201105_1649'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(choices=[('create_vk_bot', 'Создать бота в vk.com'), ('login_vk_bot', 'Авторизовать бота в vk.com'), ('create_twitter_bot', 'Создать бота в twitter.com'), ('login_twitter_bot', 'Авторизовать бота в twitter.com'), ('create_instagram_bot', 'Создать бота в instagram.com'), ('login_instagram_bot', 'Авторизовать бота в instagram.com'), ('login_instagram_bot_by_selenium', 'Авторизовать бота в instagram.com через браузер'), ('create_instagram_bot_by_selenium', 'Создать бота в instagram.com через браузер'), ('create_facebook_bot', 'Создать бота в facebook.com'), ('login_facebook_bot', 'Авторизовать бота в facebook.com'), ('create_mail_ru_bot', 'Создать бота в "Мой мир"'), ('login_mail_ru_bot', 'Авторизовать бота в "Мой мир"')], max_length=79, verbose_name='Тип задачи'),
  ),
 ]