# Generated by Django 3.1.1 on 2020-12-09 12:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

 replaces = [('lemmings_app', '0013_auto_20201209_1152'), ('lemmings_app', '0014_auto_20201209_1155'), ('lemmings_app', '0015_auto_20201209_1158'), ('lemmings_app', '0016_auto_20201209_1200')]

 dependencies = [
  ('lemmings_app', '0012_auto_20201105_1652'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(choices=[('create_vk_bot', 'Создать бота в vk.com'), ('login_vk_bot', 'Авторизовать бота в vk.com'), ('create_twitter_bot', 'Создать бота в twitter.com'), ('login_twitter_bot', 'Авторизовать бота в twitter.com'), ('create_instagram_bot', 'Создать бота в instagram.com'), ('login_instagram_bot', 'Авторизовать бота в instagram.com'), ('login_instagram_bot_by_selenium', 'Авторизовать бота в instagram.com через браузер'), ('create_instagram_bot_by_selenium', 'Создать бота в instagram.com через браузер'), ('create_facebook_bot', 'Создать бота в facebook.com'), ('login_facebook_bot', 'Авторизовать бота в facebook.com'), ('create_mail_ru_bot', 'Создать бота в "Мой мир"'), ('login_mail_ru_bot', 'Авторизовать бота в "Мой мир"'), ('create_classmates_bot', 'Создать бота в "Одноклассники"'), ('login_classmates_bot', 'Авторизовать бота в "Одноклассники"'), ('create_reddit_bot', 'создать бота в "Reddit.com"'), ('login_reddit_bot', 'Авторизовать бота в "Reddit.com"'), ('create_linkedin_bot_by_selenium', 'создать бота в "Linkedin.com" через браузер'), ('login_linkedin_bot_by_selenium', 'Авторизовать бота в "Linkedin.com" через браузер'), ('create_yandex_mail', 'создать почту в "yandex.ru"')], max_length=79, verbose_name='Тип задачи'),
  ),
  migrations.CreateModel(
   name='BotAccount',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('service', models.CharField(choices=[('VK', 'VK'), ('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM'), ('FACEBOOK', 'FACEBOOK'), ('MY_WORLD', 'MY_WORLD'), ('CLASSMATES', 'CLASSMATES'), ('REDDIT', 'REDDIT'), ('LINKEDIN', 'LINKEDIN'), ('YANDEX', 'YANDEX')], help_text='Короткое название сервиса', max_length=32)),
    ('username', models.CharField(help_text='Уникальный идентификатор в сервисе', max_length=128)),
    ('password', models.CharField(help_text='Пароль учетной записи', max_length=128)),
    ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер привязанного телефона', max_length=128, null=True, region=None)),
    ('email', models.EmailField(blank=True, help_text='Привязанная почта', max_length=254, null=True)),
    ('extra', models.JSONField(blank=True, default=dict, help_text='Прочие данные')),
   ],
  ),
 ]