# Generated by Django 3.1.4 on 2020-12-28 18:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0030_auto_20201228_1802'),
  ('lemmings_app', '0014_auto_20201209_1956'),
 ]

 operations = [
  migrations.AlterModelOptions(
   name='botaccount',
   options={'ordering': ['-id'], 'verbose_name': 'BotAccount', 'verbose_name_plural': 'BotAccounts'},
  ),
  migrations.AlterModelOptions(
   name='lemmingstask',
   options={'ordering': ['-id'], 'verbose_name': 'Lemmings task', 'verbose_name_plural': 'Lemmings tasks'},
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='email',
   field=models.EmailField(blank=True, help_text='Привязанная почта', max_length=254, null=True,
         verbose_name='email'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='extra',
   field=models.JSONField(blank=True, default=dict, help_text='Прочие данные', verbose_name='extra data'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='password',
   field=models.CharField(help_text='Пароль учетной записи', max_length=128, verbose_name='password'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='phone_number',
   field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер привязанного телефона',
                 max_length=128, null=True, region=None,
                 verbose_name='phone number'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='service',
   field=models.CharField(
    choices=[('VK', 'VK'), ('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM'), ('FACEBOOK', 'FACEBOOK'),
       ('MY_WORLD', 'MY_WORLD'), ('CLASSMATES', 'CLASSMATES'), ('REDDIT', 'REDDIT'),
       ('LINKEDIN', 'LINKEDIN'), ('YANDEX', 'YANDEX'), ('MYSPACE', 'MYSPACE')],
    help_text='Короткое название сервиса', max_length=32, verbose_name='service'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='username',
   field=models.CharField(help_text='Уникальный идентификатор в сервисе', max_length=128,
          verbose_name='username'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(
    choices=[('create_vk_bot', 'Создать бота в vk.com'), ('login_vk_bot', 'Авторизовать бота в vk.com'),
       ('create_twitter_bot', 'Создать бота в twitter.com'),
       ('login_twitter_bot', 'Авторизовать бота в twitter.com'),
       ('create_instagram_bot', 'Создать бота в instagram.com'),
       ('login_instagram_bot', 'Авторизовать бота в instagram.com'),
       ('login_instagram_bot_by_selenium', 'Авторизовать бота в instagram.com через браузер'),
       ('create_instagram_bot_by_selenium', 'Создать бота в instagram.com через браузер'),
       ('create_facebook_bot', 'Создать бота в facebook.com'),
       ('login_facebook_bot', 'Авторизовать бота в facebook.com'),
       ('create_mail_ru_bot', 'Создать бота в "Мой мир"'),
       ('login_mail_ru_bot', 'Авторизовать бота в "Мой мир"'),
       ('create_classmates_bot', 'Создать бота в "Одноклассники"'),
       ('login_classmates_bot', 'Авторизовать бота в "Одноклассники"'),
       ('create_reddit_bot', 'создать бота в "Reddit.com"'),
       ('login_reddit_bot', 'Авторизовать бота в "Reddit.com"'),
       ('create_linkedin_bot_by_selenium', 'создать бота в "Linkedin.com" через браузер'),
       ('login_linkedin_bot_by_selenium', 'Авторизовать бота в "Linkedin.com" через браузер'),
       ('create_yandex_mail', 'создать почту в "yandex.ru"'),
       ('create_myspace_bot', 'создать бота в "myspace.com"'),
       ('login_myspace_bot', 'Авторизовать бота в "myspace.com"')], max_length=79,
    verbose_name='action'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='chain',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
         related_name='lmgs_tasks', to='anon_app.chain', verbose_name='chain'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='kwargs',
   field=models.JSONField(blank=True, default=dict, verbose_name='kwargs'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='result',
   field=models.JSONField(blank=True, default=dict, verbose_name='result'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='task_id',
   field=models.CharField(max_length=128, null=True, verbose_name='task id'),
  ),
 ]