# Generated by Django 3.1.4 on 2021-01-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0015_auto_20201228_1802'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='lemmings_task',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmings_app.lemmingstask'),
  ),
 ]