# Generated by Django 3.1.4 on 2021-01-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0017_auto_20210115_1107'),
 ]

 operations = [
  migrations.AlterField(
   model_name='botaccount',
   name='service',
   field=models.CharField(choices=[('VK', 'VK'), ('TWITTER', 'TWITTER'), ('INSTAGRAM', 'INSTAGRAM'), ('FACEBOOK', 'FACEBOOK'), ('MY_WORLD', 'MY_WORLD'), ('CLASSMATES', 'CLASSMATES'), ('REDDIT', 'REDDIT'), ('LINKEDIN', 'LINKEDIN'), ('YANDEX', 'YANDEX'), ('MYSPACE', 'MYSPACE')], help_text='Короткое название сервиса', max_length=32, verbose_name='service'),
  ),
 ]