# Generated by Django 3.1.4 on 2021-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0018_auto_20210115_1117'),
 ]

 operations = [
  migrations.AlterField(
   model_name='botaccount',
   name='service',
   field=models.CharField(help_text='Короткое название сервиса', max_length=32, verbose_name='service'),
  ),
 ]