# Generated by Django 3.1.4 on 2021-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0019_auto_20210115_1125'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='banned',
   field=models.BooleanField(default=False, verbose_name='Забанен'),
  ),
  migrations.AddField(
   model_name='botaccount',
   name='enable_behavior_emulation',
   field=models.BooleanField(default=False),
  ),
  migrations.AlterUniqueTogether(
   name='botaccount',
   unique_together={('service', 'username')},
  ),
 ]