# Generated by Django 3.1.4 on 2021-01-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0020_auto_20210115_1229'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='authorized',
   field=models.BooleanField(default=False, verbose_name='Авторизован'),
  ),
  migrations.AddField(
   model_name='botaccount',
   name='last_authorize',
   field=models.DateTimeField(null=True, verbose_name='Дата последней авторизации'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='enable_behavior_emulation',
   field=models.BooleanField(default=False, verbose_name='Включить эмуляцию поведения'),
  ),
 ]