# Generated by Django 3.1.4 on 2021-01-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0021_auto_20210118_0649'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='cookies',
   field=models.JSONField(null=True, verbose_name='Куки последней сессии эмуляции поведения с помощью selenium'),
  ),
 ]