# Generated by Django 3.1.4 on 2021-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0023_auto_20210201_1153'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='stereotype',
   field=models.CharField(blank=True, choices=[('Домохозяйка', 'Домохозяйка'), ('Студент', 'Студент'), ('Офисный сотрудник', 'Офисный сотрудник'), ('Бизнесмен', 'Бизнесмен'), ('Военнослужащий', 'Военнослужащий')], max_length=64, null=True),
  ),
 ]