# Generated by Django 3.2 on 2021-04-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0050_merge_20210414_1331'),
  ('lemmings_app', '0024_auto_20210321_1727'),
 ]

 operations = [
  migrations.CreateModel(
   name='AccountPoolSetting',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('resource_name', models.CharField(
     choices=[('VK', 'vk'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'), ('FACEBOOK', 'facebook'),
        ('MY_WORLD', 'my_world'), ('CLASSMATES', 'classmates'), ('REDDIT', 'reddit'),
        ('LINKEDIN', 'linkedin'), ('YANDEX', 'yandex'), ('MYSPACE', 'myspace'),
        ('TELEGRAM', 'telegram')], default='', max_length=18, verbose_name='resource name')),
    ('needed_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='needed quantity')),
    ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon_app.chain',
           verbose_name='chain')),
   ],
   options={
    'verbose_name': 'Account Pool Setting',
    'verbose_name_plural': 'Account Pool Setting',
    'ordering': ['-id'],
   },
  ),
 ]