# Generated by Django 3.2 on 2021-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0025_accountpoolsetting'),
 ]

 operations = [
  migrations.AddField(
   model_name='accountpoolsetting',
   name='sleep_between_runs',
   field=models.IntegerField(default=0, verbose_name='sleep between runs'),
  ),
 ]