# Generated by Django 3.2.3 on 2021-06-18 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0026_accountpoolsetting_sleep_between_runs'),
 ]

 operations = [
  migrations.AddField(
   model_name='lemmingstask',
   name='birthday',
   field=models.CharField(blank=True, help_text='example: 31.12.1990', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{1,2}\\.[\\d]{1,2}\\.[\\d]{4}$')]),
  ),
  migrations.AddField(
   model_name='lemmingstask',
   name='first_name',
   field=models.CharField(blank=True, max_length=128, null=True),
  ),
  migrations.AddField(
   model_name='lemmingstask',
   name='last_name',
   field=models.CharField(blank=True, max_length=128, null=True),
  ),
  migrations.AddField(
   model_name='lemmingstask',
   name='sex',
   field=models.PositiveIntegerField(blank=True, choices=[('0', 'unknown'), ('1', 'man'), ('2', 'woman')], default='0'),
  ),
 ]