# Generated by Django 3.2 on 2021-04-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 replaces = [('lemmings_app', '0027_alter_botaccount_service'), ('lemmings_app', '0028_auto_20210426_1642'),
    ('lemmings_app', '0029_botaccount_chain')]

 dependencies = [
  ('lemmings_app', '0026_accountpoolsetting_sleep_between_runs'),
  ('anon_app', '0050_merge_20210414_1331'),
 ]

 operations = [
  migrations.AlterField(
   model_name='botaccount',
   name='service',
   field=models.CharField(
    choices=[('VK', 'vk'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'), ('FACEBOOK', 'facebook'),
       ('MY_WORLD', 'my_world'), ('CLASSMATES', 'classmates'), ('REDDIT', 'reddit'),
       ('LINKEDIN', 'linkedin'), ('YANDEX', 'yandex'), ('MYSPACE', 'myspace'),
       ('TELEGRAM', 'telegram')], default='', max_length=18, verbose_name='resource name'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='cookies',
   field=models.JSONField(blank=True, default=dict, null=True,
          verbose_name='Куки последней сессии эмуляции поведения с помощью selenium'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='lemmings_task',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
         to='lemmings_app.lemmingstask'),
  ),
  migrations.AddField(
   model_name='botaccount',
   name='chain',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
         to='anon_app.chain'),
  ),
 ]