# Generated by Django 3.2 on 2021-04-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0050_merge_20210414_1331'),
  ('lemmings_app', '0027_alter_botaccount_service_squashed_0029_botaccount_chain'),
 ]

 operations = [
  migrations.RenameField(
   model_name='accountpoolsetting',
   old_name='resource_name',
   new_name='service',
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='chain',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
         to='anon_app.chain', verbose_name='chain'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='stereotype',
   field=models.CharField(blank=True, choices=[('Домохозяйка', 'Домохозяйка'), ('Студент', 'Студент'),
              ('Офисный сотрудник', 'Офисный сотрудник'),
              ('Бизнесмен', 'Бизнесмен'),
              ('Военнослужащий', 'Военнослужащий')], max_length=64, null=True,
          verbose_name='stereotype'),
  ),
 ]