# Generated by Django 3.2.3 on 2021-06-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0027_auto_20210618_1008'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='sex',
   field=models.PositiveIntegerField(choices=[('0', 'unknown'), ('1', 'man'), ('2', 'woman')], default='0'),
  ),
 ]