# Generated by Django 3.2.3 on 2021-06-18 11:34

from django.db import migrations, models
import lemmings_app.validators


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0028_alter_lemmingstask_sex'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.CharField(blank=True, help_text='example: 31.12.1990', max_length=10, null=True, validators=[lemmings_app.validators.validate_date]),
  ),
 ]