# Generated by Django 3.1.4 on 2021-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0028_auto_20210427_1019'),
 ]

 operations = [
  migrations.AlterField(
   model_name='accountpoolsetting',
   name='service',
   field=models.CharField(
    choices=[('VK', 'vk'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'), ('FACEBOOK', 'facebook'),
       ('MY_WORLD', 'my_world'), ('CLASSMATES', 'classmates'), ('REDDIT', 'reddit'),
       ('LINKEDIN', 'linkedin'), ('YANDEX', 'yandex'), ('MYSPACE', 'myspace')], default='',
    max_length=18, verbose_name='resource name'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='service',
   field=models.CharField(
    choices=[('VK', 'vk'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'), ('FACEBOOK', 'facebook'),
       ('MY_WORLD', 'my_world'), ('CLASSMATES', 'classmates'), ('REDDIT', 'reddit'),
       ('LINKEDIN', 'linkedin'), ('YANDEX', 'yandex'), ('MYSPACE', 'myspace')], default='',
    max_length=18, verbose_name='resource name'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(
    choices=[('create_vk_bot', 'Создать бота в vk.com'), ('login_vk_bot', 'Авторизовать бота в vk.com'),
       ('create_twitter_bot', 'Создать бота в twitter.com'),
       ('login_twitter_bot', 'Авторизовать бота в twitter.com'),
       ('create_instagram_bot', 'Создать бота в instagram.com'),
       ('login_instagram_bot', 'Авторизовать бота в instagram.com'),
       ('login_instagram_bot_by_selenium', 'Авторизовать бота в instagram.com через браузер'),
       ('create_instagram_bot_by_selenium', 'Создать бота в instagram.com через браузер'),
       ('create_facebook_bot', 'Создать бота в facebook.com'),
       ('login_facebook_bot', 'Авторизовать бота в facebook.com'),
       ('create_mail_ru_bot', 'Создать бота в "Мой мир"'),
       ('login_mail_ru_bot', 'Авторизовать бота в "Мой мир"'),
       ('create_classmates_bot', 'Создать бота в "Одноклассники"'),
       ('login_classmates_bot', 'Авторизовать бота в "Одноклассники"'),
       ('create_reddit_bot', 'создать бота в "Reddit.com"'),
       ('login_reddit_bot', 'Авторизовать бота в "Reddit.com"'),
       ('create_linkedin_bot_by_selenium', 'создать бота в "Linkedin.com" через браузер'),
       ('login_linkedin_bot_by_selenium', 'Авторизовать бота в "Linkedin.com" через браузер'),
       ('create_yandex_mail', 'создать почту в "yandex.ru"'),
       ('create_myspace_bot', 'создать бота в "myspace.com"'),
       ('login_myspace_bot', 'Авторизовать бота в "myspace.com"')], max_length=79,
    verbose_name='action'),
  ),
  migrations.AddConstraint(
   model_name='accountpoolsetting',
   constraint=models.UniqueConstraint(fields=('chain', 'service'), name='unique_setting_for_chain'),
  ),
 ]