# Generated by Django 3.2.3 on 2021-06-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0033_auto_20210622_1442'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='sex',
   field=models.CharField(blank=True, choices=[('', 'unknown'), ('1', 'man'), ('2', 'woman')], default='',
          max_length=1, verbose_name='sex'),
  ),
  # migrations.AlterField(
  #  model_name='lemmingstask',
  #  name='task_id',
  #  field=models.CharField(blank=True, default='', max_length=128, verbose_name='task id'),
  # ),
 ]