# Generated by Django 3.2.3 on 2021-06-22 15:11

from django.db import migrations, models
import lemmings_app.validators


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0035_auto_20210622_1442'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.CharField(blank=True, default='', help_text='пример: 31.12.1990', max_length=10,
          validators=[lemmings_app.validators.validate_date], verbose_name='birthday'),
  ),
 ]