# Generated by Django 3.2.4 on 2021-06-23 17:03

from django.db import migrations, models
import lemmings_app.validators


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0036_alter_lemmingstask_birthday'),
 ]

 operations = [
  migrations.AddField(
   model_name='lemmingstask',
   name='birthday_datetime',
   field=models.DateField(blank=True, default='1990-12-01', help_text='пример: 31.12.1990', max_length=1000, verbose_name='birthday'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.CharField(blank=True, default='', help_text='пример: 31.12.1990', max_length=1000, validators=[lemmings_app.validators.validate_date], verbose_name='birthday'),
  ),
 ]