# Generated by Django 3.2.4 on 2021-06-23 17:15
import dateparser
from datetime import datetime, date
from django.db import migrations


def convert_str_to_datetime(apps, schema_editor):
 LemmingsTask = apps.get_model('lemmings_app', 'LemmingsTask')
 for lemmings_task in LemmingsTask.objects.all():
  try:
   birtday = dateparser.parse(lemmings_task.birthday, languages=['ru'])
   birtday.day
  except:
   birtday = datetime(year=2000, month=4, day=1)
  lemmings_task.birthday_datetime = birtday
  lemmings_task.save()


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0037_auto_20210623_1703'),
 ]

 operations = [
  migrations.RunPython(convert_str_to_datetime),
 ]