# Generated by Django 3.2.4 on 2021-06-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0038_auto_20210623_1715'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='lemmingstask',
   name='birthday',
  ),
 ]