# Generated by Django 3.2.4 on 2021-06-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0039_remove_lemmingstask_birthday'),
 ]

 operations = [
  migrations.RenameField(
   model_name='lemmingstask',
   old_name='birthday_datetime',
   new_name='birthday',
  ),
 ]