# Generated by Django 3.2.3 on 2021-06-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0040_rename_birthday_datetime_lemmingstask_birthday'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.DateField(blank=True, default='22.02.1990', help_text='пример: 31.12.1990', max_length=1000,
          verbose_name='birthday'),
  ),
 ]