# Generated by Django 3.2.3 on 2021-06-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0041_alter_lemmingstask_birthday'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='sex',
   field=models.CharField(blank=True, choices=[('', '?'), ('0', 'М'), ('1', 'Ж')], default='', max_length=1,
          verbose_name='sex'),
  ),
 ]