# Generated by Django 3.2.3 on 2021-06-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0042_alter_lemmingstask_sex'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.DateField(blank=True, default='22.02.1990', help_text='пример: 31.12.1990', null=True,
          verbose_name='birthday'),
  ),
 ]