# Generated by Django 3.2.3 on 2021-06-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0059_auto_20210623_1800'),
  ('lemmings_app', '0043_alter_lemmingstask_birthday'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='chain',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lmgs_tasks',
         to='anon_app.chain', verbose_name='chain'),
  ),
 ]