# Generated by Django 3.2.4 on 2021-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

 replaces = [('lemmings_app', '0045_alter_lemmingstask_birthday'), ('lemmings_app', '0046_alter_lemmingstask_birthday')]

 dependencies = [
  ('lemmings_app', '0044_alter_lemmingstask_chain'),
 ]

 operations = [
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.DateField(blank=True, default='', help_text='пример: 31.12.1990', null=True, verbose_name='birthday'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.DateField(blank=True, help_text='пример: 31.12.1990', null=True, verbose_name='birthday'),
  ),
 ]