# Generated by Django 3.2.4 on 2021-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0045_alter_lemmingstask_birthday_squashed_0046_alter_lemmingstask_birthday'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='how_get',
   field=models.CharField(blank=True, choices=[('0', 'Imported'), ('1', 'Generated')], max_length=1, verbose_name='How the account was obtained?'),
  ),
 ]