# Generated by Django 3.2 on 2021-07-13 13:40

from django.db import migrations


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0031_alter_botaccount_create_progress_squashed_0032_alter_botaccount_create_progress'),
  ('lemmings_app', '0046_botaccount_how_get'),
 ]

 operations = [
 ]