# Generated by Django 3.2 on 2021-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0049_auto_20210714_1323'),
 ]

 operations = [
  migrations.RemoveConstraint(
   model_name='botaccount',
   name='unique_username_in_service',
  ),
  migrations.AddConstraint(
   model_name='botaccount',
   constraint=models.UniqueConstraint(condition=models.Q(_negated=True, username=''),
             fields=('service', 'username'), name='unique_username_in_service'),
  ),
 ]