# Generated by Django 3.2 on 2021-07-15 09:09

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0050_auto_20210714_1358'),
 ]

 operations = [
  migrations.AlterField(
   model_name='botaccount',
   name='create_progress',
   field=django_fsm.FSMField(choices=[('START', 'START'), ('BIO_GENERATED', 'BIO_GENERATED'),
             ('REQUIRED_ACCOUNT_REGISTERED', 'REQUIRED_ACCOUNT_REGISTERED'),
             ('PHONE_RESERVED', 'PHONE_RESERVED'),
             ('REGISTERED_IN_SERVICE', 'REGISTERED_IN_SERVICE'),
             ('ACCOUNT_SAVED', 'ACCOUNT_SAVED'),
             ('ACCOUNT_LOGGED_IN', 'ACCOUNT_LOGGED_IN'), ('AUTH_SAVED', 'AUTH_SAVED'),
             ('SUCCESS', 'SUCCESS'), ('ERROR_BIO', 'ERROR_BIO'),
             ('ERROR_SERVICE', 'ERROR_SERVICE'),
             ('ERROR_SUB_SERVICE', 'ERROR_SUB_SERVICE'),
             ('ERROR_PHONE', 'ERROR_PHONE'), ('ERROR_DB', 'ERROR_DB')],
          default='START', max_length=50, protected=True, verbose_name='create progress'),
  ),
 ]