# Generated by Django 3.2 on 2021-07-21 13:49

from django.db import migrations


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0051_alter_botaccount_create_progress'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='botaccount',
   name='lemmings_task',
  ),
 ]