# Generated by Django 3.2 on 2021-07-29 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0053_alter_lemmingstask_action'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='dependency',
   field=models.BooleanField(default=False, verbose_name='dependency account'),
  ),
  migrations.AlterField(
   model_name='accountpoolsetting',
   name='service',
   field=models.CharField(choices=[('VK', 'вконтакте'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'),
           ('FACEBOOK', 'facebook'), ('MY_WORLD', 'мой мир'),
           ('PROTON_MAIL', 'proton_mail'), ('YAHOO_MAIL', 'yahoo_mail'),
           ('CLASSMATES', 'одноклассники'), ('REDDIT', 'reddit'),
           ('LINKEDIN', 'linkedin'), ('YANDEX', 'яндекс'), ('MYSPACE', 'myspace'),
           ('TELEGRAM', 'telegram')], default='', max_length=18,
          verbose_name='resource name'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='service',
   field=models.CharField(choices=[('VK', 'вконтакте'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'),
           ('FACEBOOK', 'facebook'), ('MY_WORLD', 'мой мир'),
           ('PROTON_MAIL', 'proton_mail'), ('YAHOO_MAIL', 'yahoo_mail'),
           ('CLASSMATES', 'одноклассники'), ('REDDIT', 'reddit'),
           ('LINKEDIN', 'linkedin'), ('YANDEX', 'яндекс'), ('MYSPACE', 'myspace'),
           ('TELEGRAM', 'telegram')], max_length=18,
          validators=[django.core.validators.MinLengthValidator(1)],
          verbose_name='resource name'),
  ),
 ]