# Generated by Django 3.2 on 2021-07-31 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0054_auto_20210729_0952'),
 ]

 operations = [
  migrations.AlterField(
   model_name='accountpoolsetting',
   name='service',
   field=models.CharField(choices=[('VK', 'вконтакте'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'),
           ('FACEBOOK', 'facebook'), ('MY_WORLD', 'мой мир'),
           ('MAIL_RU', 'mail.ru (почта)'), ('PROTON_MAIL', 'proton_mail'),
           ('YAHOO_MAIL', 'yahoo_mail'), ('CLASSMATES', 'одноклассники'),
           ('REDDIT', 'reddit'), ('LINKEDIN', 'linkedin'), ('YANDEX', 'яндекс'),
           ('MYSPACE', 'myspace'), ('TELEGRAM', 'telegram')], default='',
          max_length=18, verbose_name='resource name'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='service',
   field=models.CharField(choices=[('VK', 'вконтакте'), ('TWITTER', 'twitter'), ('INSTAGRAM', 'instagram'),
           ('FACEBOOK', 'facebook'), ('MY_WORLD', 'мой мир'),
           ('MAIL_RU', 'mail.ru (почта)'), ('PROTON_MAIL', 'proton_mail'),
           ('YAHOO_MAIL', 'yahoo_mail'), ('CLASSMATES', 'одноклассники'),
           ('REDDIT', 'reddit'), ('LINKEDIN', 'linkedin'), ('YANDEX', 'яндекс'),
           ('MYSPACE', 'myspace'), ('TELEGRAM', 'telegram')], max_length=18,
          validators=[django.core.validators.MinLengthValidator(1)],
          verbose_name='resource name'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(choices=[('create_telegram_bot', 'Создать бота в telegram'),
           ('login_telegram_bot', 'Авторизовать бота в telegram'),
           ('create_vk_bot', 'Создать бота в vk.com'),
           ('login_vk_bot', 'Авторизовать бота в vk.com'),
           ('create_twitter_bot', 'Создать бота в twitter.com'),
           ('login_twitter_bot', 'Авторизовать бота в twitter.com'), (
            'login_instagram_bot_by_selenium',
            'Авторизовать бота в instagram.com через браузер'), (
            'create_instagram_bot_by_selenium',
            'Создать бота в instagram.com через браузер'),
           ('create_facebook_bot', 'Создать бота в facebook.com'),
           ('login_facebook_bot', 'Авторизовать бота в facebook.com'),
           ('create_mail_ru_bot', 'Создать бота в "Мой мир"'),
           ('create_mail_ru_imap_bot', 'Создать почту в mail ru с паролем для imap'),
           ('login_mail_ru_bot', 'Авторизовать бота в "Мой мир"'),
           ('create_classmates_bot', 'Создать бота в "Одноклассники"'),
           ('login_classmates_bot', 'Авторизовать бота в "Одноклассники"'),
           ('create_reddit_bot', 'создать бота в "Reddit.com"'),
           ('login_reddit_bot', 'Авторизовать бота в "Reddit.com"'), (
            'create_linkedin_bot_by_selenium',
            'создать бота в "Linkedin.com" через браузер'), (
            'login_linkedin_bot_by_selenium',
            'Авторизовать бота в "Linkedin.com" через браузер'),
           ('create_yandex_mail', 'создать почту в "yandex.ru"'),
           ('create_yahoo_mail', 'Создать почту в mail.yahoo.com'),
           ('create_myspace_bot', 'создать бота в "myspace.com"'),
           ('login_myspace_bot', 'Авторизовать бота в "myspace.com"'),
           ('create_proton_mail_bot', 'создать почту в protonmail.com'),
           ('login_proton_mail_bot', 'Авторизовать почту в protonmail.com')],
          max_length=79, verbose_name='action'),
  ),
 ]