# Generated by Django 3.2.4 on 2021-08-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

 replaces = [('lemmings_app', '0056_auto_20210802_0428'), ('lemmings_app', '0057_auto_20210802_0448')]

 dependencies = [
  ('lemmings_app', '0055_auto_20210731_0939'),
 ]

 operations = [
  migrations.RemoveConstraint(
   model_name='botaccount',
   name='unique_username_in_service',
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='action',
   field=models.CharField(choices=[('create_telegram_bot', 'Создать бота в telegram'), ('login_telegram_bot', 'Авторизовать бота в telegram'), ('create_vk_bot', 'Создать бота в vk.com'), ('login_vk_bot', 'Авторизовать бота в vk.com'), ('create_twitter_bot', 'Создать бота в twitter.com'), ('login_twitter_bot', 'Авторизовать бота в twitter.com'), ('login_instagram_bot_by_selenium', 'Авторизовать бота в instagram.com через браузер'), ('create_instagram_bot_by_selenium', 'Создать бота в instagram.com через браузер'), ('create_facebook_bot', 'Создать бота в facebook.com'), ('login_facebook_bot', 'Авторизовать бота в facebook.com'), ('create_mail_ru_bot', 'Создать бота в "Мой мир"'), ('create_mail_ru_imap_bot', 'Создать почту в mail ru с паролем для imap'), ('login_mail_ru_imap_bot', 'Авторизоваться в mail ru с паролем для imap'), ('login_mail_ru_bot', 'Авторизовать бота в "Мой мир"'), ('create_classmates_bot', 'Создать бота в "Одноклассники"'), ('login_classmates_bot', 'Авторизовать бота в "Одноклассники"'), ('create_reddit_bot', 'создать бота в "Reddit.com"'), ('login_reddit_bot', 'Авторизовать бота в "Reddit.com"'), ('create_linkedin_bot_by_selenium', 'создать бота в "Linkedin.com" через браузер'), ('login_linkedin_bot_by_selenium', 'Авторизовать бота в "Linkedin.com" через браузер'), ('create_yandex_mail', 'создать почту в "yandex.ru"'), ('create_yahoo_mail', 'Создать почту в mail.yahoo.com'), ('create_myspace_bot', 'создать бота в "myspace.com"'), ('login_myspace_bot', 'Авторизовать бота в "myspace.com"'), ('create_proton_mail_bot', 'создать почту в protonmail.com'), ('login_proton_mail_bot', 'Авторизовать почту в protonmail.com')], max_length=79, verbose_name='action'),
  ),
  migrations.AddConstraint(
   model_name='botaccount',
   constraint=models.UniqueConstraint(condition=models.Q(('create_progress__in', ['START', 'BIO_GENERATED', 'REQUIRED_ACCOUNT_REGISTERED', 'PHONE_RESERVED', 'REGISTERED_IN_SERVICE', 'ERROR_BIO', 'ERROR_SERVICE', 'ERROR_SUB_SERVICE', 'ERROR_PHONE', 'ERROR_DB']), ('username', ''), _negated=True), fields=('service', 'username'), name='unique_username_in_service'),
  ),
  migrations.RemoveConstraint(
   model_name='botaccount',
   name='unique_username_in_service',
  ),
  migrations.AddConstraint(
   model_name='botaccount',
   constraint=models.UniqueConstraint(condition=models.Q(('username', ''), _negated=True), fields=('service', 'username'), name='unique_username_in_service'),
  ),
 ]