# Generated by Django 3.2 on 2021-08-02 08:16

from django.db import migrations


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0057_auto_20210802_0812'),
 ]

 operations = [
  migrations.RenameField(
   model_name='botaccount',
   old_name='how_get',
   new_name='create_type',
  ),
 ]