# Generated by Django 3.2 on 2021-08-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('lemmings_app', '0058_rename_how_get_botaccount_create_type'),
 ]

 operations = [
  migrations.AddField(
   model_name='accountpoolsetting',
   name='last_triggered_at',
   field=models.DateTimeField(blank=True, null=True),
  ),
 ]