# Generated by Django 3.2 on 2021-08-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0065_auto_20210804_1553'),
  ('lemmings_app', '0060_auto_20210804_1553'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='date_of_birth',
   field=models.DateField(blank=True, help_text='пример: 31.12.1990', null=True, verbose_name='birthday'),
  ),
  migrations.AddField(
   model_name='botaccount',
   name='first_name',
   field=models.CharField(blank=True, max_length=128, verbose_name='first_name'),
  ),
  migrations.AddField(
   model_name='botaccount',
   name='last_name',
   field=models.CharField(blank=True, max_length=128, verbose_name='last_name'),
  ),
  migrations.AddField(
   model_name='botaccount',
   name='sex',
   field=models.CharField(blank=True, choices=[('', '?'), ('0', 'М'), ('1', 'Ж')], default='', max_length=1,
          verbose_name='sex'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='chain',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anon_app.chain',
         verbose_name='chain'),
  ),
 ]