# Generated by Django 3.2.6 on 2021-08-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0062_alter_lemmingstask_action'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='last_traceback',
   field=models.TextField(blank=True, verbose_name='traceback'),
  ),
 ]