# Generated by Django 3.2.6 on 2021-08-27 08:32

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0063_botaccount_last_traceback'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='successful_auth_date',
   field=models.DateTimeField(blank=True, null=True, verbose_name='successful auth date'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='create_progress',
   field=django_fsm.FSMField(choices=[('START', 'START'), ('BIO_GENERATED', 'BIO_GENERATED'), ('REQUIRED_ACCOUNT_REGISTERED', 'REQUIRED_ACCOUNT_REGISTERED'), ('PHONE_RESERVED', 'PHONE_RESERVED'), ('REGISTERED_IN_SERVICE', 'REGISTERED_IN_SERVICE'), ('ACCOUNT_SAVED', 'ACCOUNT_SAVED'), ('ACCOUNT_LOGGED_IN', 'ACCOUNT_LOGGED_IN'), ('AUTH_SAVED', 'AUTH_SAVED'), ('SUCCESS', 'SUCCESS'), ('ERROR_BIO', 'ERROR_BIO'), ('ERROR_SERVICE', 'ERROR_SERVICE'), ('ERROR_SUB_SERVICE', 'ERROR_SUB_SERVICE'), ('ERROR_PHONE', 'ERROR_PHONE'), ('ERROR_DB', 'ERROR_DB'), ('START_PREPARE', 'START_PREPARE'), ('START_CHECK_LOGIN', 'START_CHECK_LOGIN'), ('SERVICE_ERROR', 'SERVICE_ERROR'), ('BLOCKED_ACC', 'BLOCKED_ACC')], default='START', max_length=50, protected=True, verbose_name='create progress'),
  ),
 ]