# Generated by Django 3.2.6 on 2021-09-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0065_alter_botaccount_create_progress'),
 ]

 operations = [
  migrations.RenameField(
   model_name='botaccount',
   old_name='create_progress',
   new_name='account_state',
  ),
 ]