# Generated by Django 3.2.7 on 2021-09-03 06:44

from django.db import migrations


def change_ba_status(apps, schema_editor):
 BotAccount = apps.get_model('lemmings_app', 'BotAccount')
 BotAccount.objects.filter(account_state='SUCCESS').update(account_state='READY')

class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0067_alter_botaccount_account_state'),
 ]

 operations = [
  migrations.RunPython(change_ba_status),
 ]