# Generated by Django 3.2.7 on 2021-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0069_behaviorbots'),
 ]

 operations = [
  migrations.AddField(
   model_name='behaviorbots',
   name='start_time',
   field=models.DateTimeField(blank=True, help_text='Datetime when the schedule should begin triggering the task to run', null=True, verbose_name='Start Datetime'),
  ),
 ]