# Generated by Django 3.2.7 on 2021-09-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0070_behaviorbots_start_time'),
 ]

 operations = [
  migrations.AlterModelOptions(
   name='behaviorbots',
   options={'ordering': ['-id'], 'verbose_name': 'Behavior bots', 'verbose_name_plural': 'Behaviors bots'},
  ),
 ]