# Generated by Django 3.2.7 on 2021-09-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('django_celery_beat', '0017_merge_20210421_1344'),
  ('lemmings_app', '0071_alter_behaviorbots_options'),
 ]

 operations = [
  migrations.AddField(
   model_name='behaviorbots',
   name='periodic_task',
   field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask'),
  ),
 ]