# Generated by Django 3.2.7 on 2021-09-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0072_behaviorbots_periodic_task'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='botaccount',
   name='stereotype',
  ),
  migrations.AddField(
   model_name='botaccount',
   name='behavior_bot',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmings_app.behaviorbots', verbose_name='Behavior bot'),
  ),
  migrations.AlterField(
   model_name='botaccount',
   name='date_of_birth',
   field=models.DateField(blank=True, help_text='example: 31.12.1990', null=True, verbose_name='birthday'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.DateField(blank=True, help_text='example: 31.12.1990', null=True, verbose_name='birthday'),
  ),
 ]