# Generated by Django 3.2.7 on 2021-09-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0073_auto_20210909_1525'),
 ]

 operations = [
  migrations.AlterField(
   model_name='botaccount',
   name='date_of_birth',
   field=models.DateField(blank=True, help_text='пример: 31.12.1990', null=True, verbose_name='birthday'),
  ),
  migrations.AlterField(
   model_name='lemmingstask',
   name='birthday',
   field=models.DateField(blank=True, help_text='пример: 31.12.1990', null=True, verbose_name='birthday'),
  ),
 ]