# Generated by Django 3.2.8 on 2021-10-12 09:24

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0074_auto_20210910_0801'),
 ]

 operations = [
  migrations.AlterField(
   model_name='botaccount',
   name='account_state',
   field=django_fsm.FSMField(choices=[('START', 'START'), ('BIO_GENERATED', 'BIO_GENERATED'), ('REQUIRED_ACCOUNT_REGISTERED', 'REQUIRED_ACCOUNT_REGISTERED'), ('PHONE_RESERVED', 'PHONE_RESERVED'), ('REGISTERED_IN_SERVICE', 'REGISTERED_IN_SERVICE'), ('ACCOUNT_SAVED', 'ACCOUNT_SAVED'), ('ACCOUNT_LOGGED_IN', 'ACCOUNT_LOGGED_IN'), ('AUTH_SAVED', 'AUTH_SAVED'), ('READY', 'READY'), ('ERROR_BIO', 'ERROR_BIO'), ('ERROR_SERVICE', 'ERROR_SERVICE'), ('ERROR_SUB_SERVICE', 'ERROR_SUB_SERVICE'), ('ERROR_PHONE', 'ERROR_PHONE'), ('ERROR_DB', 'ERROR_DB'), ('START_CHECK_LOGIN', 'START_CHECK_LOGIN'), ('ERROR_SERVICE_CHECK', 'ERROR_SERVICE_CHECK'), ('BLOCKED_ACC', 'BLOCKED_ACC'), ('ACCOUNT_BUSY', 'ACCOUNT_BUSY'), ('ACCOUNT_RESERVED', 'ACCOUNT_RESERVED')], default='START', max_length=50, protected=True, verbose_name='create progress'),
  ),
 ]