# Generated by Django 3.2.8 on 2021-10-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0075_alter_botaccount_account_state'),
 ]

 operations = [
  migrations.AddField(
   model_name='accountpoolsetting',
   name='amount_of_attempts_to_create_accounts',
   field=models.PositiveSmallIntegerField(default=0, verbose_name='Amount of attempts to create accounts'),
  ),
 ]