# Generated by Django 3.2.8 on 2021-10-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0076_accountpoolsetting_amount_of_attempts_to_create_accounts'),
 ]

 operations = [
  migrations.AddField(
   model_name='accountpoolsetting',
   name='behavior_bot',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lemmings_app.behaviorbots', verbose_name='Behavior bot'),
  ),
 ]