# Generated by Django 3.2.9 on 2021-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0077_accountpoolsetting_behavior_bot'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='changed',
   field=models.DateTimeField(auto_now=True, null=True, verbose_name='changed'),
  ),
 ]