# Generated by Django 3.2.9 on 2021-12-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0078_botaccount_changed'),
 ]

 operations = [
  migrations.AddField(
   model_name='accountpoolsetting',
   name='is_need_set_behavior',
   field=models.BooleanField(default=True, verbose_name='is need to set behavior'),
  ),
 ]