# Generated by Django 3.2.9 on 2022-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0079_accountpoolsetting_is_need_set_behavior'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='created',
   field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='account created'),
  ),
 ]