# Generated by Django 3.2.11 on 2022-01-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0080_botaccount_created'),
 ]

 operations = [
  migrations.AddField(
   model_name='accountpoolsetting',
   name='need_to_notification',
   field=models.BooleanField(default=True, verbose_name='send notification'),
  ),
 ]