# Generated by Django 3.2.11 on 2022-01-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0081_accountpoolsetting_need_to_notification'),
  ('lemmings_app', '0081_auto_20220126_1522'),
 ]

 operations = [
 ]