# Generated by Django 3.2.14 on 2022-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0085_auto_20220524_1009'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='needs_new_mail',
   field=models.BooleanField(default=False, verbose_name='Register new e-mail'),
  ),
 ]