# Generated by Django 3.2.18 on 2023-07-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('lemmings_app', '0087_auto_20230321_2159'),
 ]

 operations = [
  migrations.AddField(
   model_name='botaccount',
   name='location',
   field=models.CharField(blank=True, null=True, help_text='Местоположение бота', max_length=128, verbose_name='location'),
  ),
 ]