# Generated by Django 3.2.3 on 2021-05-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 initial = True

 dependencies = [
 ]

 operations = [
  migrations.CreateModel(
   name='Currency',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('name', models.CharField(max_length=128, verbose_name='Название валюты')),
   ],
   options={
    'verbose_name': 'Currency',
    'verbose_name_plural': 'Currencies',
    'ordering': ['-id'],
   },
  ),
  migrations.CreateModel(
   name='PaidService',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('name', models.CharField(max_length=128, verbose_name='Название сервиса')),
    ('url', models.URLField(verbose_name='Ссылка на сервис')),
    ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
   ],
   options={
    'verbose_name': 'Paid Service',
    'verbose_name_plural': 'Paid Service',
    'ordering': ['-id'],
   },
  ),
  migrations.CreateModel(
   name='ServiceAccount',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('username', models.CharField(max_length=32, verbose_name='username')),
    ('password', models.CharField(max_length=128, verbose_name='password')),
    ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_app.paidservice', verbose_name='Сервис')),
   ],
   options={
    'verbose_name': 'Service Account',
    'verbose_name_plural': 'Service Account',
   },
  ),
  migrations.CreateModel(
   name='Ledger',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('balance', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Баланс')),
    ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_app.serviceaccount', verbose_name='Аккаунт сервиса')),
    ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_app.currency', verbose_name='Валюта')),
    ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_app.paidservice', verbose_name='Сервис')),
   ],
   options={
    'verbose_name': 'Ledger',
    'verbose_name_plural': 'Ledger',
    'ordering': ['-id'],
   },
  ),
 ]