# Generated by Django 3.2.3 on 2021-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0001_initial'),
 ]

 operations = [
  migrations.AlterField(
   model_name='paidservice',
   name='note',
   field=models.TextField(blank=True, default='', verbose_name='Заметка'),
   preserve_default=False,
  ),
 ]