# Generated by Django 3.2.6 on 2021-09-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 replaces = [('ledger_app', '0003_phonerent_phonerentaccount'), ('ledger_app', '0004_alter_phonerentaccount_options')]

 dependencies = [
  ('ledger_app', '0002_alter_paidservice_note'),
 ]

 operations = [
  migrations.CreateModel(
   name='PhoneRent',
   fields=[
    ('paidservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger_app.paidservice')),
    ('rent_service_type', models.CharField(choices=[('SMS_ACTIVATE', 'SMS_ACTIVATE'), ('NOT_SMS_ACTIVATE', 'NOT_SMS_ACTIVATE')], default='SMS_ACTIVATE', max_length=20)),
   ],
   options={
    'verbose_name': 'PhoneRent',
    'verbose_name_plural': 'PhoneRents',
    'ordering': ['-id'],
   },
   bases=('ledger_app.paidservice',),
  ),
  migrations.CreateModel(
   name='PhoneRentAccount',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('username', models.CharField(max_length=32, verbose_name='username')),
    ('password', models.CharField(max_length=128, verbose_name='password')),
    ('api_key', models.CharField(blank=True, default='', max_length=128)),
    ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_app.phonerent', verbose_name='Сервис аренды телефонов')),
   ],
   options={
    'verbose_name': 'PhoneRentAccount',
    'verbose_name_plural': 'PhoneRentAccounts',
    'abstract': False,
    'ordering': ['-id'],
   },
  ),
 ]