# Generated by Django 3.2.7 on 2021-09-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0003_phonerent_phonerentaccount_squashed_0004_alter_phonerentaccount_options'),
 ]

 operations = [
  migrations.AlterModelOptions(
   name='phonerent',
   options={'ordering': ['-id'], 'verbose_name': 'Rent service', 'verbose_name_plural': 'Rent services'},
  ),
  migrations.AlterField(
   model_name='phonerent',
   name='rent_service_type',
   field=models.CharField(choices=[('SMS_ACTIVATE', 'SMS_ACTIVATE'), ('Other service', 'Other service')], default='SMS_ACTIVATE', max_length=20, verbose_name='Rent service type'),
  ),
  migrations.AlterField(
   model_name='phonerentaccount',
   name='api_key',
   field=models.CharField(max_length=128),
  ),
  migrations.AlterField(
   model_name='phonerentaccount',
   name='service',
   field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_app.phonerent', verbose_name='Rent service'),
  ),
 ]