# Generated by Django 3.2.7 on 2021-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0004_auto_20210903_1327'),
 ]

 operations = [
  migrations.AlterField(
   model_name='phonerent',
   name='rent_service_type',
   field=models.CharField(choices=[('SMS_ACTIVATE', 'SMS_ACTIVATE'), ('SMS_MAN', 'SMS_MAN'), ('ONLINE_SIM', 'ONLINE_SIM')], default='SMS_ACTIVATE', max_length=20, verbose_name='Rent service type'),
  ),
 ]