# Generated by Django 3.2.7 on 2021-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0005_alter_phonerent_rent_service_type'),
 ]

 operations = [
  migrations.AddField(
   model_name='phonerentaccount',
   name='available',
   field=models.BooleanField(default=True, verbose_name='Available?'),
  ),
  migrations.AddField(
   model_name='phonerentaccount',
   name='balance',
   field=models.DecimalField(decimal_places=12, default=0, max_digits=30, verbose_name='Balance'),
   preserve_default=False,
  ),
 ]