# Generated by Django 3.2.7 on 2021-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0006_auto_20210913_1000'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='phonerentaccount',
   name='available',
  ),
  migrations.AddField(
   model_name='phonerentaccount',
   name='account_state',
   field=models.CharField(choices=[('available', 'available'), ('NOT_AVAILABLE', 'not available'), ('bad_key', 'bad key'), ('error_sql', 'error sql')], default='available', max_length=128, verbose_name='Account state'),
  ),
 ]