# Generated by Django 3.2.7 on 2021-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0007_auto_20210913_1111'),
 ]

 operations = [
  migrations.AlterField(
   model_name='phonerentaccount',
   name='balance',
   field=models.DecimalField(decimal_places=12, default=0.0, max_digits=30, verbose_name='Balance'),
  ),
 ]