# Generated by Django 3.2.7 on 2021-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0008_alter_phonerentaccount_balance'),
 ]

 operations = [
  migrations.AlterField(
   model_name='phonerentaccount',
   name='account_state',
   field=models.CharField(choices=[('available', 'available'), ('not_available', 'not available'), ('bad_key', 'bad key'), ('error_sql', 'error sql')], default='available', max_length=128, verbose_name='Account state'),
  ),
 ]