# Generated by Django 3.2.8 on 2021-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0009_alter_phonerentaccount_account_state'),
 ]

 operations = [
  migrations.AlterField(
   model_name='phonerent',
   name='rent_service_type',
   field=models.CharField(choices=[('SMS_ACTIVATE', 'SMS_ACTIVATE'), ('SMS_MAN', 'SMS_MAN'), ('ONLINE_SIM', 'ONLINE_SIM'), ('SMS_365', 'SMS_365')], default='SMS_ACTIVATE', max_length=20, verbose_name='Rent service type'),
  ),
 ]