# Generated by Django 3.2.11 on 2022-01-21 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0010_alter_phonerent_rent_service_type'),
 ]

 operations = [
  migrations.AddField(
   model_name='currency',
   name='show_numbers',
   field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Количество чисел после запятой'),
  ),
  migrations.AlterField(
   model_name='ledger',
   name='balance',
   field=models.DecimalField(decimal_places=24, max_digits=57, verbose_name='Баланс'),
  ),
 ]