# Generated by Django 3.2.11 on 2022-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0011_auto_20220121_1037'),
 ]

 operations = [
  migrations.AlterField(
   model_name='phonerentaccount',
   name='balance',
   field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Balance'),
  ),
 ]