# Generated by Django 3.0.2 on 2020-05-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 initial = True

 dependencies = [
 ]

 operations = [
  migrations.CreateModel(
   name='Chain',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('title', models.CharField(max_length=120)),
   ],
  ),
  migrations.CreateModel(
   name='Hosting',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('name', models.CharField(max_length=128)),
    ('hosting_url', models.URLField()),
   ],
  ),
  migrations.CreateModel(
   name='Server',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('ssh_ip', models.GenericIPAddressField()),
    ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon_app.Hosting')),
   ],
  ),
  migrations.CreateModel(
   name='SrvAccount',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('username', models.CharField(max_length=32)),
    ('password', models.CharField(max_length=128)),
    ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_account', to='anon_app.Server')),
   ],
  ),
  migrations.CreateModel(
   name='Node',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('certificate', models.FileField(blank=True, default='', upload_to='')),
    ('geo', models.CharField(max_length=128)),
    ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anon_app.Server')),
   ],
  ),
  migrations.CreateModel(
   name='HostingAccount',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('username', models.CharField(max_length=32)),
    ('password', models.CharField(max_length=128)),
    ('hosting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_account', to='anon_app.Hosting')),
   ],
  ),
  migrations.CreateModel(
   name='Edge',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('protocol', models.CharField(choices=[('ssh', 'ssh')], default='ssh', max_length=64)),
    ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='anon_app.Chain')),
    ('in_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_node_set', to='anon_app.Node')),
    ('out_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_node_set', to='anon_app.Node')),
   ],
  ),
 ]