# Generated by Django 3.0.5 on 2020-07-08 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0001_initial'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='task_queue_name',
   field=models.CharField(default='external_celery', max_length=120),
   preserve_default=False,
  ),
  migrations.AddField(
   model_name='node',
   name='ssh_proc_port',
   field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
  ),
 ]