# Generated by Django 3.0.8 on 2020-07-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0002_chain_task_queue_name'),
 ]

 operations = [
  migrations.CreateModel(
   name='AppImage',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('name', models.CharField(max_length=120)),
    ('path', models.FilePathField(match='so[si]{1}_web-app\\.tar$', path='/tmp/', recursive=True),),
   ],
  ),
  migrations.AlterField(
   model_name='chain',
   name='task_queue_name',
   field=models.CharField(default='external_celery', max_length=120),
  ),
  migrations.AddField(
   model_name='chain',
   name='app_image',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anon_app.AppImage'),
  ),
 ]