# Generated by Django 3.0.8 on 2020-07-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0003_auto_20200720_1233_squashed_0005_auto_20200722_0704'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='node',
   name='certificate',
  ),
  migrations.AddField(
   model_name='node',
   name='id_rsa',
   field=models.FileField(default='/tmp/id_rsa', upload_to=''),
  ),
  migrations.AddField(
   model_name='node',
   name='id_rsa_pub',
   field=models.FileField(default='/tmp/id_rsa.pub', upload_to=''),
  ),
 ]