# Generated by Django 3.0.8 on 2020-08-06 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0004_auto_20200723_1643'),
 ]

 operations = [
  migrations.AddField(
   model_name='appimage',
   name='docker_compose',
   field=models.FileField(default='stub', upload_to=''),
   preserve_default=False,
  ),
  migrations.AddField(
   model_name='appimage',
   name='env',
   field=models.FileField(default='stub', upload_to=''),
   preserve_default=False,
  ),
  migrations.AddField(
   model_name='appimage',
   name='openssh_container_external_port',
   field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1024),
                  django.core.validators.MaxValueValidator(65535)]),
   preserve_default=False,
  ),
  migrations.AddField(
   model_name='appimage',
   name='openssh_container_id_rsa',
   field=models.FileField(default='stub', upload_to=''),
   preserve_default=False,
  ),
  migrations.AddField(
   model_name='appimage',
   name='openssh_container_id_rsa_pub',
   field=models.FileField(default='stub', upload_to=''),
   preserve_default=False,
  ),
  migrations.AddField(
   model_name='appimage',
   name='openssh_container_internal_port',
   field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1024),
                  django.core.validators.MaxValueValidator(65535)]),
   preserve_default=False,
  ),
 ]