# Generated by Django 3.1 on 2020-08-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0005_auto_20200806_1336'),
 ]

 operations = [
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa',
   field=models.FileField(null=True, upload_to=''),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa_pub',
   field=models.FileField(null=True, upload_to=''),
  ),
  migrations.AlterField(
   model_name='node',
   name='id_rsa',
   field=models.FileField(null=True, upload_to=''),
  ),
  migrations.AlterField(
   model_name='node',
   name='id_rsa_pub',
   field=models.FileField(null=True, upload_to=''),
  ),
 ]