# Generated by Django 3.1 on 2020-08-13 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0006_auto_20200811_0959'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='process_ids',
   field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
  ),
  migrations.AddField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('IN_PROCESS', 'В процессе создания'), ('CREATED', 'Создан'), ('FAILED', 'Не удалось создать')], default='IN_PROCESS', max_length=16),
  ),
 ]