# Generated by Django 3.1 on 2020-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0007_auto_20200813_0820'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован')], default='CREATING', max_length=128),
  ),
 ]