# Generated by Django 3.1 on 2020-08-19 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0008_auto_20200819_0821'),
 ]

 operations = [
  migrations.AddField(
   model_name='appimage',
   name='browser_profiles',
   field=models.FileField(default='/path/to/not/found', help_text='ZIP архив с профилями браузеров (в архиве должны содержаться две директории: firefox и chrome, каждая из которых в свою очередь содержит некоторое кол-во директорий, являющихся профилями соответствующих браузеров)', upload_to=''),
   preserve_default=False,
  ),
  migrations.AddField(
   model_name='appimage',
   name='title',
   field=models.CharField(default='best-chain', help_text='Название образа, допустимо любое значение', max_length=120),
   preserve_default=False,
  ),
  migrations.AlterField(
   model_name='appimage',
   name='docker_compose',
   field=models.FileField(help_text='Текстовый файл в формате yml, описывает запуск сервисов, брать актуальную версию можно из /path/to/soi/end-node', upload_to=''),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='env',
   field=models.FileField(help_text='Текстовый файл формата env, описывает переменные окружающей среды, брать актуальную версию можно из /path/to/soi/end-node', upload_to=''),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='image',
   field=models.FileField(help_text='ZIP архив, содержащий в себе tar файл, который представляет собой docker образ приложения', upload_to=''),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='name',
   field=models.CharField(help_text='Имя образа, данное ему при создании (пр.: sos_web-app)', max_length=120),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_external_port',
   field=models.PositiveIntegerField(help_text='Порт на котором будет доступен ssh сервер контейнера openssh на удаленном хосте', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa',
   field=models.FileField(help_text='Приватный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то создастся автоматически)', null=True, upload_to=''),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa_pub',
   field=models.FileField(help_text='Публичный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то создастся автоматически)', null=True, upload_to=''),
  ),
 ]