# Generated by Django 3.1.1 on 2020-10-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0009_auto_20200819_1751'),
 ]

 operations = [
  migrations.AddField(
   model_name='node',
   name='is_tor',
   field=models.BooleanField(default=False, help_text='Узел обеспечивает проксирование соединения через Tor?'),
  ),
 ]