# Generated by Django 3.1.1 on 2020-10-16 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0010_node_is_tor'),
 ]

 operations = [
  migrations.AddField(
   model_name='node',
   name='ssh_port',
   field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
  ),
 ]