# Generated by Django 3.1.1 on 2020-10-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0011_node_ssh_port'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='node',
   name='is_tor',
  ),
  migrations.AlterField(
   model_name='edge',
   name='protocol',
   field=models.CharField(choices=[('SSH', 'ssh'), ('SSH_VIA_TOR', 'ssh via tor')], default='SSH', max_length=64),
  ),
 ]