# Generated by Django 3.1.1 on 2020-10-22 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0012_auto_20201022_0623'),
 ]

 operations = [
  migrations.AddField(
   model_name='server',
   name='ssh_port',
   field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
  ),
 ]