# Generated by Django 3.1.2 on 2020-10-28 07:43

from django.db import migrations


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0013_server_ssh_port'),
 ]

 operations = [
  migrations.AlterModelOptions(
   name='appimage',
   options={'ordering': ['-id']},
  ),
  migrations.AlterModelOptions(
   name='chain',
   options={'ordering': ['-id']},
  ),
  migrations.AlterModelOptions(
   name='edge',
   options={'ordering': ['-id']},
  ),
  migrations.AlterModelOptions(
   name='hosting',
   options={'ordering': ['-id']},
  ),
  migrations.AlterModelOptions(
   name='hostingaccount',
   options={'ordering': ['-id']},
  ),
  migrations.AlterModelOptions(
   name='node',
   options={'ordering': ['-id']},
  ),
  migrations.AlterModelOptions(
   name='server',
   options={'ordering': ['-id']},
  ),
  migrations.AlterModelOptions(
   name='srvaccount',
   options={'ordering': ['-id']},
  ),
 ]