# Generated by Django 3.1.1 on 2020-11-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0013_server_ssh_port'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='chain',
   name='process_ids',
  ),
 ]