# Generated by Django 3.1.2 on 2020-10-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0014_auto_20201028_0743'),
 ]

 operations = [
  migrations.AlterField(
   model_name='node',
   name='server',
   field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anon_app.server'),
  ),
 ]