# Generated by Django 3.1.2 on 2020-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0015_auto_20201028_1205'),
 ]

 operations = [
  migrations.AddConstraint(
   model_name='server',
   constraint=models.UniqueConstraint(fields=('ssh_ip',), name='unique ip'),
  ),
 ]