# Generated by Django 3.1.3 on 2020-11-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0016_auto_20201028_1602'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='fake_remove',
   field=models.BooleanField(default=False),
  ),
  migrations.AlterField(
   model_name='chain',
   name='app_image',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
         to='anon_app.appimage'),
  ),
  migrations.AlterField(
   model_name='chain',
   name='task_queue_name',
   field=models.CharField(default='external_celery', max_length=120, unique=True),
  ),
 ]