# Generated by Django 3.1.1 on 2020-11-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0017_auto_20201103_1215'),
  ('anon_app', '0014_remove_chain_process_ids'),
 ]

 operations = [
 ]