# Generated by Django 3.1.1 on 2020-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0018_merge_20201105_1649'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается')], default='CREATING', max_length=128),
  ),
 ]