# Generated by Django 3.1.1 on 2020-11-12 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0019_auto_20201105_1652'),
 ]

 operations = [
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_external_port',
   field=models.PositiveIntegerField(help_text='Порт на котором будет доступен ssh сервер контейнера openssh на удаленном хосте', null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_internal_port',
   field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
  ),
 ]