# Generated by Django 3.1.4 on 2020-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0020_auto_20201112_1414'),
 ]

 operations = [
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa',
   field=models.FileField(default='',
          help_text='Приватный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то создастся автоматически)',
          upload_to=''),
   preserve_default=False,
  ),
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa_pub',
   field=models.FileField(default='',
          help_text='Публичный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то создастся автоматически)',
          upload_to=''),
   preserve_default=False,
  ),
 ]