# Generated by Django 3.1.4 on 2020-12-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0021_auto_20201201_1351'),
 ]

 operations = [
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa',
   field=models.FileField(
    help_text='Приватный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то '
       'создастся автоматически)',
    null=True, upload_to=''),
  ),
  migrations.AlterField(
   model_name='appimage',
   name='openssh_container_id_rsa_pub',
   field=models.FileField(
    help_text='Публичный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то '
       'создастся автоматически)',
    null=True, upload_to=''),
  ),
 ]