# Generated by Django 3.1.4 on 2020-12-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

 replaces = [('anon_app', '0023_proxy'), ('anon_app', '0024_auto_20201209_0915'), ('anon_app', '0025_auto_20201209_0917'), ('anon_app', '0026_auto_20201209_0926'), ('anon_app', '0027_auto_20201209_0932'), ('anon_app', '0028_proxy_fill_method'), ('anon_app', '0029_auto_20201209_1525'), ('anon_app', '0030_auto_20201210_0655')]

 dependencies = [
  ('anon_app', '0022_auto_20201202_1252'),
 ]

 operations = [
  migrations.CreateModel(
   name='Proxy',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('ip', models.CharField(default='1.2.3.4', max_length=128)),
    ('location', models.CharField(default='ru', max_length=128)),
    ('password', models.CharField(blank=True, max_length=128, null=True)),
    ('port', models.CharField(default=1234, max_length=128)),
    ('protocol', models.CharField(default='http', max_length=128)),
    ('username', models.CharField(blank=True, max_length=128, null=True)),
   ],
   options={
    'ordering': ['-id'],
   },
  ),
 ]