# Generated by Django 3.1.4 on 2020-12-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0023_proxy_squashed_0030_auto_20201210_0655'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='ip',
   field=models.CharField(max_length=128),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='location',
   field=models.CharField(max_length=128),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='port',
   field=models.CharField(max_length=128),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='protocol',
   field=models.CharField(max_length=128),
  ),
 ]