# Generated by Django 3.1.4 on 2020-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0024_auto_20201210_0700'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='protocol',
   field=models.CharField(choices=[('FTP', 'ftp'), ('HTTP', 'http'), ('HTTPS', 'https'), ('Socks4', 'socks4'), ('Socks5', 'socks5'), ('SMTP', 'smpt'), ('POP3', 'pop3'), ('IMAP', 'imap')], max_length=128),
  ),
 ]