# Generated by Django 3.1.4 on 2020-12-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0025_auto_20201210_0738'),
 ]

 operations = [
  migrations.AddField(
   model_name='proxy',
   name='file',
   field=models.FileField(default=1, help_text='CVS файл с информацией о proxy', upload_to=''),
   preserve_default=False,
  ),
  migrations.AlterField(
   model_name='proxy',
   name='password',
   field=models.CharField(blank=True, help_text='Необзятальеое поле', max_length=128, null=True),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='protocol',
   field=models.CharField(choices=[('FTP', 'ftp'), ('HTTP', 'http'), ('HTTPS', 'https'), ('Socks4', 'socks4'), ('Socks5', 'socks5'), ('SMTP', 'smtp'), ('POP3', 'pop3'), ('IMAP', 'imap')], help_text='Тип протокола', max_length=128),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='username',
   field=models.CharField(blank=True, help_text='Необзятальеое поле', max_length=128, null=True),
  ),
 ]