# Generated by Django 3.1.4 on 2020-12-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0025_auto_20201210_0738'),
 ]

 operations = [
  migrations.AddField(
   model_name='appimage',
   name='filebeat_config',
   field=models.FileField(default='',
          help_text='Файл в формате yml для получение сообщений из файлов журналов удалённых узлов',
          upload_to=''),
   preserve_default=False,
  ),
 ]