# Generated by Django 3.1.4 on 2020-12-14 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0025_auto_20201210_0738'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='appimage',
   name='openssh_container_external_port',
  ),
  migrations.RemoveField(
   model_name='appimage',
   name='openssh_container_id_rsa',
  ),
  migrations.RemoveField(
   model_name='appimage',
   name='openssh_container_id_rsa_pub',
  ),
  migrations.RemoveField(
   model_name='appimage',
   name='openssh_container_internal_port',
  ),
  migrations.AddField(
   model_name='chain',
   name='openssh_container_external_port',
   field=models.PositiveIntegerField(help_text='Порт на котором будет доступен ssh сервер контейнера openssh на удаленном хосте', null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
  ),
  migrations.AddField(
   model_name='chain',
   name='openssh_container_id_rsa',
   field=models.FileField(help_text='Приватный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то создастся автоматически)', null=True, upload_to=''),
  ),
  migrations.AddField(
   model_name='chain',
   name='openssh_container_id_rsa_pub',
   field=models.FileField(help_text='Публичный ключ для доступа к удаленному контейнеру с openssh (если не указывать, то создастся автоматически)', null=True, upload_to=''),
  ),
  migrations.AddField(
   model_name='chain',
   name='openssh_container_internal_port',
   field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)]),
  ),
  migrations.AlterField(
   model_name='chain',
   name='task_queue_name',
   field=models.CharField(max_length=120, unique=True),
  ),
 ]