# Generated by Django 3.1.4 on 2020-12-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0026_auto_20201214_0930'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='proxy',
   name='file',
  ),
  migrations.AlterField(
   model_name='proxy',
   name='password',
   field=models.CharField(blank=True, max_length=128, null=True),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='protocol',
   field=models.CharField(choices=[('FTP', 'ftp'), ('HTTP', 'http'), ('HTTPS', 'https'), ('Socks4', 'socks4'), ('Socks5', 'socks5'), ('SMTP', 'smtp'), ('POP3', 'pop3'), ('IMAP', 'imap')], max_length=128),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='username',
   field=models.CharField(blank=True, max_length=128, null=True),
  ),
 ]