# Generated by Django 3.1.4 on 2020-12-17 13:43

from django.db import migrations


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0026_auto_20201214_1755'),
  ('anon_app', '0027_auto_20201215_0938'),
 ]

 operations = [
 ]