# Generated by Django 3.1.4 on 2020-12-22 11:59

from django.db import migrations


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0026_appimage_filebeat_config'),
  ('anon_app', '0028_merge_20201217_1343'),
 ]

 operations = [
 ]