# Generated by Django 3.1.4 on 2021-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0030_auto_20201228_1802'),
 ]

 operations = [
  migrations.AlterField(
   model_name='edge',
   name='protocol',
   field=models.CharField(choices=[('SOCKS', 'SOCKS'), ('TOR', 'TOR'), ('VPN', 'VPN')], default='SOCKS', max_length=64, verbose_name='protocol'),
  ),
 ]