# Generated by Django 3.1.4 on 2021-02-04 13:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0031_auto_20210111_1154'),
 ]

 operations = [
  migrations.AddField(
   model_name='node',
   name='ovpn_netmask',
   field=models.GenericIPAddressField(null=True, verbose_name='OpenVPN netmask'),
  ),
  migrations.AddField(
   model_name='node',
   name='ovpn_network',
   field=models.GenericIPAddressField(null=True, verbose_name='OpenVPN network'),
  ),
  migrations.AddField(
   model_name='node',
   name='ovpn_port',
   field=models.PositiveIntegerField(default=1194, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='OpenVPN port'),
  ),
  migrations.CreateModel(
   name='OpenVPNClient',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('sub_network', models.GenericIPAddressField(default='', verbose_name='Subnet which is routed to OpenVPN network')),
    ('sub_netmask', models.GenericIPAddressField(default='', verbose_name='Mask of subnet which is routed to OpenVPN network')),
    ('client', models.CharField(max_length=128, verbose_name='OpenVPN client name')),
    ('config', models.FileField(upload_to='', verbose_name='OpenVPN client config file')),
    ('client_ip', models.GenericIPAddressField(verbose_name='Client IP in OpenVPN network')),
    ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovpn_clients_set', to='anon_app.node', verbose_name='Node')),
   ],
   options={
    'verbose_name': 'OpenVPN client',
    'verbose_name_plural': 'OpenVPN clients',
    'ordering': ['-id'],
   },
  ),
 ]