# Generated by Django 3.1.4 on 2021-02-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
 replaces = [('anon_app', '0032_chain_proxy'), ('anon_app', '0033_auto_20210201_0907')]

 dependencies = [
  ('anon_app', '0031_auto_20210111_1154'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='proxy',
   field=models.ManyToManyField(blank=True, to='anon_app.Proxy', verbose_name='proxy'),
  ),
 ]