# Generated by Django 3.1.4 on 2021-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0032_auto_20210204_1331'),
 ]

 operations = [
  migrations.AddField(
   model_name='node',
   name='ovpn_srv_ip',
   field=models.GenericIPAddressField(null=True, verbose_name='Client IP in OpenVPN network'),
  ),
 ]