# Generated by Django 3.1.4 on 2021-02-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0032_chain_proxy_squashed_0033_auto_20210201_0907'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='chain',
   name='proxy',
  ),
  migrations.AddField(
   model_name='proxy',
   name='chain',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
         to='anon_app.chain'),
  ),
 ]