# Generated by Django 3.1.4 on 2021-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0033_node_ovpn_srv_ip'),
 ]

 operations = [
  migrations.AlterField(
   model_name='node',
   name='ovpn_srv_ip',
   field=models.GenericIPAddressField(null=True, verbose_name='Server IP in OpenVPN network'),
  ),
 ]