# Generated by Django 3.1.4 on 2021-02-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0033_auto_20210205_1231'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'),
           ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'),
           ('REBUILD_CONNECTION', 'Соединение перестраивается'),
           ('RELOAD_IMAGE', 'Загрузка нового образа')], default='CREATING',
          max_length=128, verbose_name='status'),
  ),
 ]