# Generated by Django 3.1.4 on 2021-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0034_auto_20210204_1511'),
 ]

 operations = [
  migrations.AlterField(
   model_name='node',
   name='ovpn_netmask',
   field=models.GenericIPAddressField(default='255.255.255.0', verbose_name='OpenVPN netmask'),
  ),
  migrations.AlterField(
   model_name='node',
   name='ovpn_network',
   field=models.GenericIPAddressField(default='10.0.0.0', verbose_name='OpenVPN network'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='client_ip',
   field=models.GenericIPAddressField(null=True, verbose_name='Client IP in OpenVPN network'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='config',
   field=models.FileField(null=True, upload_to='', verbose_name='OpenVPN client config file'),
  ),
 ]