# Generated by Django 3.1.4 on 2021-02-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0035_auto_20210208_2021'),
 ]

 operations = [
  migrations.AlterField(
   model_name='openvpnclient',
   name='sub_netmask',
   field=models.GenericIPAddressField(null=True, verbose_name='Mask of subnet which is routed to OpenVPN network'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='sub_network',
   field=models.GenericIPAddressField(null=True, verbose_name='Subnet which is routed to OpenVPN network'),
  ),
 ]