# Generated by Django 3.1.4 on 2021-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0036_auto_20210208_2035'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='is_for_private_network',
   field=models.BooleanField(default=False, verbose_name='is for access to private network'),
  ),
 ]