# Generated by Django 3.1.4 on 2021-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0037_chain_is_for_private_network'),
 ]

 operations = [
  migrations.AddField(
   model_name='openvpnclient',
   name='is_private',
   field=models.BooleanField(default=False, verbose_name='is for access to private network'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='client',
   field=models.CharField(max_length=128, null=True, verbose_name='OpenVPN client name'),
  ),
 ]