# Generated by Django 3.1.4 on 2021-02-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0038_auto_20210215_2104'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('PRE_CREATING', 'Предсоздаваемое состояние'), ('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]