# Generated by Django 3.1.4 on 2021-02-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0039_auto_20210215_2329'),
 ]

 operations = [
  migrations.AddField(
   model_name='node',
   name='is_for_private_network',
   field=models.BooleanField(default=False, verbose_name='is for access to private network'),
  ),
 ]