# Generated by Django 3.1.4 on 2021-02-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0040_node_is_for_private_network'),
 ]

 operations = [
  migrations.AddField(
   model_name='openvpnclient',
   name='celery_task_id',
   field=models.CharField(blank=True, max_length=128, null=True),
  ),
  migrations.AlterField(
   model_name='node',
   name='ovpn_srv_ip',
   field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Server IP in OpenVPN network'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='client',
   field=models.CharField(blank=True, max_length=128, null=True, verbose_name='OpenVPN client name'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='client_ip',
   field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP in OpenVPN network'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='config',
   field=models.FileField(blank=True, null=True, upload_to='', verbose_name='OpenVPN client config file'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='sub_netmask',
   field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Mask of subnet which is routed to OpenVPN network'),
  ),
  migrations.AlterField(
   model_name='openvpnclient',
   name='sub_network',
   field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Subnet which is routed to OpenVPN network'),
  ),
 ]