# Generated by Django 3.1.4 on 2021-02-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0034_auto_20210208_0906'),
  ('anon_app', '0041_auto_20210217_1944'),
 ]

 operations = [
 ]