# Generated by Django 3.1.4 on 2021-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0042_merge_20210217_2201'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('PRE_CREATING', 'Предсоздаваемое состояние'), ('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается'), ('RELOAD_IMAGE', 'Загрузка нового образа')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]