# Generated by Django 3.1.4 on 2021-02-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0043_auto_20210217_2202'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='node',
   name='ssh_port',
  ),
 ]