# Generated by Django 3.1.4 on 2021-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0044_remove_node_ssh_port'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='chain',
   name='is_for_private_network',
  ),
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается'), ('RELOAD_IMAGE', 'Загрузка нового образа')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]