# Generated by Django 3.1.7 on 2021-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0045_auto_20210224_1351'),
 ]

 operations = [
  migrations.AddField(
   model_name='proxy',
   name='is_alive',
   field=models.BooleanField(blank=True, default=None, help_text='Статус доступности прокси сервера', null=True),
  ),
 ]