# Generated by Django 3.1.4 on 2021-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0045_auto_20210224_1351'),
 ]

 operations = [
  migrations.AddField(
   model_name='appimage',
   name='zabbix_client_config',
   field=models.FileField(default="None", upload_to='', verbose_name='zabbix client config'),
   preserve_default=False,
  ),
 ]