# Generated by Django 3.1.4 on 2021-03-31 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0046_appimage_zabbix_client_config'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='zabbix_agent_internal_port',
   field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='internal zabbix agent port'),
  ),
 ]