# Generated by Django 3.1.4 on 2021-04-01 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0047_chain_zabbix_agent_internal_port'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='appimage',
   name='zabbix_client_config',
  ),
  migrations.RemoveField(
   model_name='chain',
   name='zabbix_agent_internal_port',
  ),
  migrations.AddField(
   model_name='node',
   name='forwarded_zabbix_port',
   field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='forwarded zabbix port'),
  ),
 ]