# Generated by Django 3.1.4 on 2021-04-02 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0048_auto_20210401_1748'),
 ]

 operations = [
  migrations.AlterField(
   model_name='node',
   name='forwarded_zabbix_port',
   field=models.PositiveIntegerField(default=10051, null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='forwarded zabbix port'),
  ),
 ]