# Generated by Django 3.1.7 on 2021-04-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0049_auto_20210402_1711'),
  ('anon_app', '0046_proxy_is_alive'),
 ]

 operations = [
 ]