# Generated by Django 3.1.7 on 2021-04-30 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0050_merge_20210414_1331'),
 ]

 operations = [
  migrations.AlterField(
   model_name='node',
   name='geo',
   field=models.CharField(blank=True, max_length=128, null=True, verbose_name='geo'),
  ),
  migrations.AlterField(
   model_name='node',
   name='id_rsa',
   field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ssh private key'),
  ),
  migrations.AlterField(
   model_name='node',
   name='id_rsa_pub',
   field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ssh public key'),
  ),
  migrations.AlterField(
   model_name='node',
   name='ssh_proc_port',
   field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='ssh proc port'),
  ),
 ]