# Generated by Django 3.1.7 on 2021-04-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0051_auto_20210430_1027'),
 ]

 operations = [
  migrations.AlterField(
   model_name='edge',
   name='in_node',
   field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_node_edges', to='anon_app.node', verbose_name='in_node'),
  ),
  migrations.AlterField(
   model_name='edge',
   name='out_node',
   field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_node_edges', to='anon_app.node', verbose_name='out_node'),
  ),
 ]