# Generated by Django 3.2.3 on 2021-05-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0052_auto_20210430_1359'),
 ]

 operations = [
  migrations.AlterModelOptions(
   name='hostingaccount',
   options={'verbose_name': 'Hosting account', 'verbose_name_plural': 'Hosting accounts'},
  ),
  migrations.RenameField(
   model_name='hosting',
   old_name='hosting_url',
   new_name='url',
  ),
 ]