# Generated by Django 3.2.3 on 2021-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0052_auto_20210430_1359'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='node',
   name='geo',
  ),
  migrations.AddField(
   model_name='server',
   name='geo',
   field=models.CharField(blank=True, default='', max_length=128, verbose_name='geo'),
  ),
 ]