# Generated by Django 3.2.3 on 2021-05-27 18:08

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0001_initial'),
  ('anon_app', '0053_auto_20210527_1646'),
 ]

 operations = [
  migrations.AddField(
   model_name='hosting',
   name='paidservice_ptr',
   field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger_app.paidservice'),
  ),
 ]