# Generated by Django 3.2.3 on 2021-05-27 18:09

from django.db import migrations

def copy_hosting_to_paid_service(apps, schema_editor):
 Hosting = apps.get_model('anon_app', 'Hosting')
 PaidService = apps.get_model('ledger_app', 'PaidService')
 hostings = Hosting.objects.all()
 for hosting in hostings:
  paid_obj = PaidService.objects.create(name=hosting.name, url=hosting.url)
  hosting.paidservice_ptr = paid_obj
  hosting.save()


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0054_hosting_paidservice_ptr'),
 ]

 operations = [
  migrations.RunPython(copy_hosting_to_paid_service),
 ]