# Generated by Django 3.2.3 on 2021-05-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('ledger_app', '0001_initial'),
  ('anon_app', '0055_auto_20210527_1809'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='hosting',
   name='id',
  ),
  migrations.RemoveField(
   model_name='hosting',
   name='name',
  ),
  migrations.RemoveField(
   model_name='hosting',
   name='url',
  ),
  migrations.AlterField(
   model_name='hosting',
   name='paidservice_ptr',
   field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger_app.paidservice'),
  ),
 ]