# Generated by Django 3.2 on 2021-05-31 15:07

from django.db import migrations


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0053_auto_20210528_1403'),
  ('anon_app', '0056_auto_20210527_1816'),
 ]

 operations = [
 ]