# Generated by Django 3.2.3 on 2021-06-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0057_merge_0053_auto_20210528_1403_0056_auto_20210527_1816'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='proxy',
   name='is_alive',
  ),
  migrations.AddField(
   model_name='proxy',
   name='state',
   field=models.CharField(blank=True, choices=[('ALIVE', 'alive'), ('DIED', 'died'), ('UNKNOWN', 'unknown'), ('CHECKING', 'checking'), ('CHECKING_FAILED', 'checking failed')], default='UNKNOWN', max_length=128, verbose_name='Proxy state'),
  ),
 ]