# Generated by Django 3.2.4 on 2021-06-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0058_auto_20210601_0153'),
 ]

 operations = [
  migrations.AlterField(
   model_name='openvpnclient',
   name='celery_task_id',
   field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Celery task id'),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='chain',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anon_app.chain', verbose_name='chain'),
  ),
 ]