# Generated by Django 3.2.3 on 2021-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0059_auto_20210623_1800'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='download_speed',
   field=models.CharField(blank=True, max_length=32, null=True),
  ),
  migrations.AddField(
   model_name='chain',
   name='last_update_info_dt',
   field=models.DateTimeField(blank=True, null=True),
  ),
  migrations.AddField(
   model_name='chain',
   name='ping',
   field=models.CharField(blank=True, max_length=32, null=True),
  ),
  migrations.AddField(
   model_name='chain',
   name='ports_info',
   field=models.JSONField(blank=True, default=dict),
  ),
  migrations.AddField(
   model_name='chain',
   name='upload_speed',
   field=models.CharField(blank=True, max_length=32, null=True),
  ),
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается'), ('RELOAD_IMAGE', 'Загрузка нового образа'), ('DIED', 'Недоступен')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]