# Generated by Django 3.2.4 on 2021-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0059_auto_20210623_1800'),
 ]

 operations = [
  migrations.AddField(
   model_name='proxy',
   name='comment',
   field=models.TextField(blank=True, verbose_name='Comment'),
  ),
  migrations.AddField(
   model_name='proxy',
   name='secure_flag',
   field=models.CharField(blank=True, choices=[('1', 'Paid proxy'), ('0', 'Free proxy')], max_length=1, verbose_name='Secure flag'),
  ),
 ]