# Generated by Django 3.2.3 on 2021-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0060_auto_20210713_1111'),
 ]

 operations = [
  migrations.AddField(
   model_name='edge',
   name='download_speed',
   field=models.CharField(blank=True, max_length=32, null=True),
  ),
  migrations.AddField(
   model_name='edge',
   name='ping',
   field=models.CharField(blank=True, max_length=32, null=True),
  ),
  migrations.AddField(
   model_name='edge',
   name='upload_speed',
   field=models.CharField(blank=True, max_length=32, null=True),
  ),
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается'), ('RELOAD_IMAGE', 'Загрузка нового образа'), ('TEST', 'Тестируется'), ('DIED', 'Недоступен')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]