# Generated by Django 3.2.3 on 2021-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0061_auto_20210714_1511'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='download_speed',
   field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Downloading speed'),
  ),
  migrations.AlterField(
   model_name='chain',
   name='last_update_info_dt',
   field=models.DateTimeField(blank=True, null=True, verbose_name='Last testing datetime'),
  ),
  migrations.AlterField(
   model_name='chain',
   name='ping',
   field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ping'),
  ),
  migrations.AlterField(
   model_name='chain',
   name='ports_info',
   field=models.JSONField(blank=True, default=dict, verbose_name='Port states'),
  ),
  migrations.AlterField(
   model_name='chain',
   name='upload_speed',
   field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Uploading speed'),
  ),
  migrations.AlterField(
   model_name='edge',
   name='download_speed',
   field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Downloading speed'),
  ),
  migrations.AlterField(
   model_name='edge',
   name='ping',
   field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ping'),
  ),
  migrations.AlterField(
   model_name='edge',
   name='upload_speed',
   field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Uploading speed'),
  ),
 ]