# Generated by Django 3.2.3 on 2021-07-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0060_auto_20210712_1245'),
  ('anon_app', '0062_auto_20210715_1414'),
 ]

 operations = [
 ]