# Generated by Django 3.2.5 on 2021-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0063_merge_0060_auto_20210712_1245_0062_auto_20210715_1414'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='last_checking_celery_task_id',
   field=models.UUIDField(null=True, verbose_name='ID задачи тестирования celery'),
  ),
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается'), ('RELOAD_IMAGE', 'Загрузка нового образа'), ('TEST_FROM_READY', 'Тестируется (была жива)'), ('TEST_FROM_DIED', 'Тестируется (была мертва)'), ('DIED', 'Недоступен')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]