# Generated by Django 3.2 on 2021-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
 dependencies = [
  ('anon_app', '0064_auto_20210719_1335'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='last_checking_celery_task_id',
   field=models.UUIDField(blank=True, null=True, verbose_name='ID задачи тестирования celery'),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='secure_flag',
   field=models.CharField(blank=True, choices=[('PAID', 'Paid proxy'), ('FREE', 'Free proxy')], max_length=4,
          verbose_name='Secure flag'),
  ),
 ]