# Generated by Django 3.2.6 on 2021-08-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0065_auto_20210804_1553'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='protocol',
   field=models.CharField(choices=[('ftp', 'ftp'), ('http', 'http'), ('https', 'https'), ('socks4', 'socks4'), ('socks5', 'socks5'), ('smtp', 'smtp'), ('pop3', 'pop3'), ('imap', 'imap')], max_length=128, verbose_name='protocol'),
  ),
 ]