# Generated by Django 3.2.6 on 2021-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0065_auto_20210804_1553'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается'), ('RELOAD_IMAGE', 'Загрузка нового образа'), ('TEST_FROM_READY', 'Тестируется (была жива)'), ('TEST_FROM_DIED', 'Тестируется (была мертва)'), ('DIED', 'Недоступен'), ('TEST', 'Тестируется')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]