# Generated by Django 3.2.6 on 2021-08-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0066_alter_chain_status'),
  ('anon_app', '0066_alter_proxy_protocol'),
 ]

 operations = [
 ]