# Generated by Django 3.2.6 on 2021-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0067_merge_20210831_2123'),
 ]

 operations = [
  migrations.AddField(
   model_name='proxy',
   name='applying',
   field=models.CharField(blank=True, choices=[('USED', 'Used proxy'), ('UNUSED', 'Unused proxy')], max_length=128, verbose_name='Applying'),
  ),
  migrations.AddField(
   model_name='proxy',
   name='number_of_applying',
   field=models.CharField(blank=True, choices=[('DISPOSABLE', 'Disposable proxy'), ('REUSABLE', 'Reusable proxy')], max_length=128, verbose_name='Number of applying'),
  ),
  migrations.AddField(
   model_name='proxy',
   name='source',
   field=models.CharField(default='', max_length=128, verbose_name='source'),
   preserve_default=False,
  ),
 ]