# Generated by Django 3.2.6 on 2021-09-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0068_auto_20210903_1432'),
 ]

 operations = [
  migrations.AddField(
   model_name='proxy',
   name='import_csv_format',
   field=models.CharField(choices=[('IP:port', 'IP:port'), ('IP:port:login:password', 'IP:port:login:password'), ('login:password:IP:port:location', 'login:password:IP:port:location')], default='', max_length=128, verbose_name='CSV format'),
  ),
 ]