# Generated by Django 3.2.6 on 2021-09-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0069_proxy_import_csv_format'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='proxy',
   name='import_csv_format',
  ),
 ]