# Generated by Django 3.2.6 on 2021-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0070_remove_proxy_import_csv_format'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='source',
   field=models.CharField(blank=True, max_length=128, verbose_name='source'),
  ),
 ]