# Generated by Django 3.2.6 on 2021-09-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0071_alter_proxy_source'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='protocol',
   field=models.CharField(choices=[('http', 'http'), ('https', 'https'), ('socks4', 'socks4'), ('socks5', 'socks5')], max_length=128, verbose_name='protocol'),
  ),
 ]