# Generated by Django 3.2.7 on 2021-09-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0072_alter_proxy_protocol'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='applying',
   field=models.CharField(blank=True, choices=[('USED', 'Used proxy'), ('UNUSED', 'Unused proxy'), ('BLACKLIST', 'Blacklist')], max_length=128, verbose_name='Applying'),
  ),
 ]