# Generated by Django 3.2.8 on 2021-10-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0073_alter_proxy_applying'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='check_proxy_limit',
   field=models.BooleanField(default=False, verbose_name='Check proxy limit'),
  ),
  migrations.AddField(
   model_name='chain',
   name='proxy_limit',
   field=models.PositiveSmallIntegerField(default=10, verbose_name='Proxy limit'),
  ),
 ]