# Generated by Django 3.2.8 on 2021-10-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0074_auto_20211012_1321'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='need_pull_accounts',
   field=models.BooleanField(default=False, verbose_name='Is it necessary to create a pool of accounts?'),
  ),
 ]