# Generated by Django 3.2.8 on 2021-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0075_chain_need_pull_accounts'),
 ]

 operations = [
  migrations.AddField(
   model_name='server',
   name='is_powerful',
   field=models.BooleanField(default=False, verbose_name='Is powerful?'),
  ),
 ]