# Generated by Django 3.2.7 on 2021-10-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0076_server_is_powerful'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='applying',
   field=models.CharField(choices=[('USED', 'Used proxy'), ('UNUSED', 'Unused proxy'), ('BLACKLIST', 'Blacklist')], max_length=128, verbose_name='Applying'),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='chain',
   field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anon_app.chain', verbose_name='chain'),
  ),
  migrations.AlterField(
   model_name='proxy',
   name='number_of_applying',
   field=models.CharField(choices=[('DISPOSABLE', 'Disposable proxy'), ('REUSABLE', 'Reusable proxy')], max_length=128, verbose_name='Number of applying'),
  ),
 ]