# Generated by Django 3.2.8 on 2021-11-17 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0077_auto_20211018_1432'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='concurrency',
   field=models.PositiveIntegerField(default=0, help_text='default 0 - one thread one core', validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='concurrency'),
  ),
 ]