# Generated by Django 3.2.7 on 2021-12-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0078_chain_concurrency'),
 ]

 operations = [
  migrations.AlterField(
   model_name='proxy',
   name='protocol',
   field=models.CharField(choices=[('', '---------'), ('unknown', 'неизвестно'), ('http', 'http'), ('https', 'https'), ('socks4', 'socks4'), ('socks5', 'socks5')], max_length=128, verbose_name='protocol'),
  ),
 ]