# Generated by Django 3.2.11 on 2022-01-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0078_chain_concurrency'),
 ]

 operations = [
  migrations.AlterField(
   model_name='chain',
   name='fake_remove',
   field=models.BooleanField(default=False, verbose_name='activity'),
  ),
 ]