# Generated by Django 3.2.11 on 2022-01-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0079_alter_chain_fake_remove'),
  ('anon_app', '0079_alter_proxy_protocol'),
 ]

 operations = [
 ]