# Generated by Django 3.2.11 on 2022-01-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0080_merge_20220120_1216'),
 ]

 operations = [
  migrations.AddField(
   model_name='server',
   name='anonymization_chain',
   field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='anon_app.chain', verbose_name='anonymization chain'),
  ),
  migrations.AddField(
   model_name='server',
   name='type',
   field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Output', 'Output'), ('Intermediate', 'Intermediate')], max_length=128, verbose_name='type'),
  ),
 ]