# Generated by Django 3.2.11 on 2022-01-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0081_auto_20220124_0943'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='chain',
   name='fake_remove',
  ),
  migrations.AlterField(
   model_name='chain',
   name='status',
   field=models.CharField(choices=[('CREATING', 'В процессе создания'), ('WORKER_DONT_RESPONSE', 'Воркер не отвечает'), ('READY', 'Готов к работе'), ('CREATING_FAILED', 'Не удалось создать'), ('BLOCK', 'Заблокирован'), ('REBUILD_CONNECTION', 'Соединение перестраивается'), ('RELOAD_IMAGE', 'Загрузка нового образа'), ('TEST_FROM_READY', 'Тестируется (была жива)'), ('TEST_FROM_DIED', 'Тестируется (была мертва)'), ('DIED', 'Недоступен'), ('TEST', 'Тестируется')], default='CREATING', max_length=128, verbose_name='status'),
  ),
 ]