# Generated by Django 3.2.7 on 2022-01-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0082_auto_20220125_1353'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='for_internet_access',
   field=models.BooleanField(default=False, verbose_name='Internet access chain'),
  ),
  migrations.AddField(
   model_name='chain',
   name='openvpn_config',
   field=models.FileField(blank=True, help_text='Конфигурационный файл OpenVPN для подключения к удаленному узлу', null=True, upload_to='', verbose_name='Configuration file OpenVPN'),
  ),
 ]