# Generated by Django 3.2.12 on 2022-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0083_auto_20220127_1423'),
 ]

 operations = [
  migrations.AddField(
   model_name='openvpnclient',
   name='is_issued',
   field=models.BooleanField(default=False, verbose_name='Was issued'),
  ),
  migrations.AddField(
   model_name='openvpnclient',
   name='openvpn_client_user',
   field=models.CharField(blank=True, max_length=128, verbose_name='Issued to whom'),
  ),
 ]