# Generated by Django 3.2.7 on 2022-04-07 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0084_auto_20220216_1355'),
 ]

 operations = [
  migrations.AddField(
   model_name='chain',
   name='has_proxies_chain',
   field=models.BooleanField(default=False, verbose_name='Use proxies chain'),
  ),
  migrations.AddField(
   model_name='chain',
   name='proxies_in_chain',
   field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Amount of proxies for building proxies chain'),
  ),
 ]