# Generated by Django 3.2.18 on 2023-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0085_auto_20220407_1237'),
 ]

 operations = [
  migrations.AddField(
   model_name='proxy',
   name='last_check_dt',
   field=models.DateTimeField(blank=True, null=True, verbose_name='Last proxy testing datetime'),
  ),
  migrations.AddField(
   model_name='proxy',
   name='last_successful_check_dt',
   field=models.DateTimeField(blank=True, null=True, verbose_name='Last successful proxy testing datetime'),
  ),
 ]