# Generated by Django 3.2.19 on 2023-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0086_auto_20230317_1621'),
 ]

 operations = [
  migrations.AddField(
   model_name='proxy',
   name='services',
   field=models.JSONField(blank=True, default=dict, verbose_name='services'),
  ),
 ]