# Generated by Django 3.2.20 on 2023-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0087_proxy_services'),
 ]

 operations = [
  migrations.AddField(
   model_name='appimage',
   name='created_date',
   field=models.DateTimeField(auto_now_add=True, null=True),
  ),
 ]