# Generated by Django 3.2.20 on 2023-08-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('anon_app', '0088_appimage_created_date'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='appimage',
   name='created_date',
  ),
 ]