# Generated by Django 3.2.7 on 2021-09-15 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications_app.models


class Migration(migrations.Migration):

 initial = True

 dependencies = [
  migrations.swappable_dependency(settings.AUTH_USER_MODEL),
 ]

 operations = [
  migrations.CreateModel(
   name='Notification',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('color', models.CharField(choices=[(notifications_app.models.Notification.TextColors['COLOR_DANGER'], 'Danger'), (notifications_app.models.Notification.TextColors['COLOR_WARNING'], 'Warning'), (notifications_app.models.Notification.TextColors['COLOR_SUCCESS'], 'Success'), (notifications_app.models.Notification.TextColors['COLOR_INFO'], 'Info'), (notifications_app.models.Notification.TextColors['COLOR_PRIMARY'], 'Primary'), (notifications_app.models.Notification.TextColors['COLOR_GRAY'], 'Gray'), (notifications_app.models.Notification.TextColors['COLOR_BLACK'], 'Black')], default=notifications_app.models.Notification.TextColors['COLOR_BLACK'], max_length=7, verbose_name='color')),
    ('content', models.TextField(max_length=256, verbose_name='content')),
    ('seen_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='seen date')),
    ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='send date')),
    ('created_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
   ],
   options={
    'verbose_name': 'Notification',
    'verbose_name_plural': 'Notifications',
    'ordering': ['-id'],
   },
  ),
 ]