# Generated by Django 3.2.7 on 2021-09-15 09:40

from django.db import migrations, models
import notifications_app.models


class Migration(migrations.Migration):

 dependencies = [
  ('notifications_app', '0001_initial'),
 ]

 operations = [
  migrations.AlterField(
   model_name='notification',
   name='color',
   field=models.CharField(choices=[('#f56954', 'Danger'), ('#f39c12', 'Warning'), ('#00a65a', 'Success'), ('#00c0ef', 'Info'), ('#3c8dbc', 'Primary'), ('#d2d6de', 'Gray'), ('#111111', 'Black')], default=notifications_app.models.Notification.TextColors['COLOR_BLACK'], max_length=7, verbose_name='color'),
  ),
 ]