# Generated by Django 3.2.7 on 2021-09-15 09:45

from django.db import migrations, models
import notifications_app.models


class Migration(migrations.Migration):

 dependencies = [
  ('notifications_app', '0002_alter_notification_color'),
 ]

 operations = [
  migrations.AlterField(
   model_name='notification',
   name='color',
   field=models.CharField(choices=[(notifications_app.models.Notification.TextColors['COLOR_DANGER'], 'Danger'), (notifications_app.models.Notification.TextColors['COLOR_WARNING'], 'Warning'), (notifications_app.models.Notification.TextColors['COLOR_SUCCESS'], 'Success'), (notifications_app.models.Notification.TextColors['COLOR_INFO'], 'Info'), (notifications_app.models.Notification.TextColors['COLOR_PRIMARY'], 'Primary'), (notifications_app.models.Notification.TextColors['COLOR_GRAY'], 'Gray'), (notifications_app.models.Notification.TextColors['COLOR_BLACK'], 'Black')], default=notifications_app.models.Notification.TextColors['COLOR_BLACK'], max_length=7, verbose_name='color'),
  ),
 ]