# Generated by Django 3.2.7 on 2021-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('notifications_app', '0004_alter_notification_color'),
 ]

 operations = [
  migrations.AlterField(
   model_name='notification',
   name='seen_date',
   field=models.DateTimeField(blank=True, null=True, verbose_name='seen date'),
  ),
 ]