# Generated by Django 3.2.7 on 2021-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('notifications_app', '0005_alter_notification_seen_date'),
 ]

 operations = [
  migrations.AddField(
   model_name='notification',
   name='error',
   field=models.CharField(blank=True, max_length=256, verbose_name='error'),
  ),
  migrations.AddField(
   model_name='notification',
   name='traceback',
   field=models.TextField(blank=True, verbose_name='traceback'),
  ),
 ]