# Generated by Django 3.2.7 on 2021-09-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

 dependencies = [
  ('notifications_app', '0007_alter_notification_color'),
 ]

 operations = [
  migrations.RemoveField(
   model_name='notification',
   name='color',
  ),
 ]