# Generated by Django 3.2.7 on 2021-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('notifications_app', '0008_remove_notification_color'),
 ]

 operations = [
  migrations.AddField(
   model_name='notification',
   name='log_level',
   field=models.CharField(choices=[('#f39c12', 'Warning'), ('#f56954', 'Danger'), ('#00c0ef', 'Info'), ('#00a65a', 'Success')], default='#00c0ef', max_length=7, verbose_name='log level'),
  ),
 ]