# Generated by Django 3.2.7 on 2021-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

 dependencies = [
  ('notifications_app', '0009_notification_log_level'),
 ]

 operations = [
  migrations.AlterField(
   model_name='notification',
   name='content',
   field=models.TextField(max_length=512, verbose_name='content'),
  ),
  migrations.AlterField(
   model_name='notification',
   name='error',
   field=models.CharField(blank=True, max_length=1024, verbose_name='error'),
  ),
 ]