# Generated by Django 3.2.16 on 2022-11-07 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ('notifications_app', '0010_auto_20211004_1711'),
 ]

 operations = [
  migrations.CreateModel(
   name='NotificationsEnabling',
   fields=[
    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('enabled', models.BooleanField(default=True)),
    ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
   ],
   options={
    'verbose_name': 'Notifications enabling',
    'verbose_name_plural': 'Notifications enabling',
    'ordering': ['-id'],
   },
  ),
  migrations.AddConstraint(
   model_name='notificationsenabling',
   constraint=models.UniqueConstraint(fields=('user', 'enabled'), name='unique_notifications_enabling'),
  ),
 ]