# Generated by Django 3.2.18 on 2023-03-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

 dependencies = [
  migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ('notifications_app', '0011_auto_20221107_0937'),
 ]

 operations = [
  migrations.AlterField(
   model_name='notificationsenabling',
   name='enabled',
   field=models.BooleanField(default=True, verbose_name='enabled'),
  ),
  migrations.AlterField(
   model_name='notificationsenabling',
   name='user',
   field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
  ),
 ]